### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#1]
I've just worked on a Dockerfile to containerize this application :
- based on the image [java:8](https://hub.docker.com/_/java/)
- [Docker Hub](https://hub.docker.com/u/jhipster/) : it can be automated or manually to the JHipster organization

Command to launch the container (currently, on my local) :
```shell
docker run -p 8761:8761 -d jhipster/jhipster-registry
```

@jdubois : can I add it to Docker Hub JHipster organization and should I configure Docker Hub to automated this application ?
cc @PierreBesson too because I don't know if you work on the registry

With this new image, we'll be able to test gateway / microservices (https://github.com/jhipster/generator-jhipster/issues/2804)

**Comment by PierreBesson** [comment]
I think that this is what we need. Just waiting for @jdubois to confirm.

**Comment by jdubois** [comment]
Hi @pascalgrimaud yes this is what we need, great!
BTW, shouldn't we move to Alpine Linux, it looks like it's what everyone is migrating to, has it's very light

**Comment by pascalgrimaud** [comment]
Of course we should !
Ok, so let's do it. I will PR as soon as it's ready => need to rework with Alpine

**Comment by pascalgrimaud** [comment]
Just finished the Dockerfile, based on [official alpine:3.3](https://hub.docker.com/_/alpine/), inspired from [anapsix/alpine-java](https://hub.docker.com/r/anapsix/alpine-java/)
=> I always prefer using a based official image

It worked before my rebase, and after rebase, the app.jar can't start => probably https://github.com/jhipster/jhipster-registry/issues/4

@PierreBesson : I have not enought time to investigate this issue. So as soon as you resolve it, ping me plz and I will PR :smile:

**Comment by PierreBesson** [comment]
OK, I will look into that.

**Comment by PierreBesson** [comment]
@pascalgrimaud it's fixed now.

**Comment by pascalgrimaud** [comment]
Thanks @PierreBesson !
I will do my PR tonight (I can't during day work...)

**Comment by pascalgrimaud** [comment]
The image is online on Docker Hub : [jhipster/jhipster-registry](https://hub.docker.com/r/jhipster/jhipster-registry/)
Not sure it's totally automated ; need probably to do the same webhook

**Comment by jdubois** [comment]
Well, there is a new image that was automatically created, do I need to do something else?

**Comment by pascalgrimaud** [comment]
Yes @jdubois, probably same thing with generator-jhipster : add the trigger token/url from Docker Hub to Github>Settings>Webhooks & Services>Add Webhooks

**Comment by jdubois** [comment]
OK, I just did it and it triggered a build

**Comment by pascalgrimaud** [comment]
Perfect ! Thanks Julien

**Comment by kozla13** [comment]
i run 
docker run -d -p 8761:8761 --restart=always jhipster/jhipster-registry:latest
but cant login:
Failed to sign in! Please check your credentials and try again.

**Comment by PierreBesson** [comment]
@kozla13 Please correctly read the documentation.

**Comment by pascalgrimaud** [comment]
@kozla13 :

1) look at your Docker logs, you should see this message:
```
----------------------------------------------------------
2017-12-31 21:59:28.713 ERROR 7 --- [           main] i.g.j.registry.JHipsterRegistryApp       : 
----------------------------------------------------------
Your JWT secret key is not set up, you will not be able to log into the JHipster.
Please read the documentation at http://www.jhipster.tech/jhipster-registry/
----------------------------------------------------------
```

2) use this, instead: `docker run -d -p 8761:8761 -e JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET=toto --restart=always jhipster/jhipster-registry:latest`
