### ISSUE TITLE
Base Dockerfile on pre-build java alpine image 

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#11]
Currently our Dockerfile does all the work to install Java on an alpine base image. This is taking some time when (re)building the image.

I think we could speed-up the build if we based our Dockerfile on something like : [anapsix/docker-alpine-java](https://github.com/anapsix/docker-alpine-java). @pascalgrimaud, I think it might be your inspiration for the image anyway. Also, it will be annoying to upgrade the version number ourselves so I suggest that we base our image on `anapsix/alpine-java` while we wait for an official java image based on Alpine. What do you think ?

**Comment by pascalgrimaud** [comment]
It's my personnal choice... I did it because it's not an official image. 
We could use anapsix/alpine-java as based image, it will work but our image will depend on this non official image.
It's same problem like using external libraries. Lot of stars ? Very active ?

**Comment by pascalgrimaud** [comment]
I have no preference :-)

**Comment by jdubois** [comment]
I'd rather base our image on an official image. Imagine the other image has any kind of trojan horse or bot in it.... I'm currently discussing about using this at my client site, I don't want to take any risk.

**Comment by PierreBesson** [comment]
Yes it would be safer to base it on a java official image. But it would triple the size of the image (see [this comparison](https://imagelayers.io/?images=anapsix%2Falpine-java:latest,java:8,anapsix%2Falpine-java:latest,jhipster%2Fjhipster-registry:latest)). If we start to build local images of all our microservices we will quickly see the benefits of keeping images as small as possible.
Our best bet is to wait for an official java alpine image to come out, hopefully before the release of JH3.

May I suggest that as a temporary solution we create our own image under the jhipster organisation. Maybe a fork of anapsix' image that we would carefully review before syncing. That would be quite easy to set up.

**Comment by pascalgrimaud** [comment]
This current Dockerfile => optimize the size

@PierreBesson : another solution. I can write a new Dockerfile (only for dev) which can be used locally => so it will speed up the build, and you don't have to wait Docker Hub to finish to build

**Comment by PierreBesson** [comment]
@pascalgrimaud I know :smile:... Please do it if you think it will speedup the build and it does not take too much of your time. I asked this because I am currently experimenting in building docker images for jhipster microservice, gateway, etc and starting them all at once with docker-compose.

**Comment by pascalgrimaud** [comment]
oh I see, I try to do it as soon as I can 
About building microservice and gateway, do you have a look at my module generator-jhipster-docker ? It should containerize the gateway and microservice apps

**Comment by PierreBesson** [comment]
Yes. Everything I do is inspired by your docker module.

**Comment by pascalgrimaud** [comment]
@PierreBesson : maybe can we close this issue ?

**Comment by PierreBesson** [comment]
Sure. You can close it.

Le dim. 6 mars 2016 18:29, Pascal Grimaud <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
only you can :-)

**Comment by PierreBesson** [comment]
You're right !
