### ISSUE TITLE
Fix the docker image build

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#111]
Currently the prod build is broken which means that when running the "develop" docker image (`docker run -p 8761:8761 jhipster/jhipster-registry:develop`), you get a blank page 😢 .

This should be fixed and using the recent advances in the generator we should even have minification and Angular 4 improvements.

**Comment by JulienMrgrd** [comment]
The blank page is probably due to the PR #110.

**Comment by PierreBesson** [comment]
@JulienMrgrd also this: https://github.com/jhipster/jhipster-registry/blob/develop/Dockerfile#L12
should be changed to `./mvnw package -Pprod`

**Comment by jdubois** [comment]
I reverted the commit, can you check once the Docker image is built?

**Comment by jdubois** [comment]
It's fixed now, as I'm using it
