### ISSUE TITLE
Update to latest JHipster revision and lint

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-registry#117]
The generated code needs to be synced with latest JHipster version and needs to be linted as currently there are lot of code quality/consistency issues

cc @jdubois I think we need to do a review before the release

**Comment by jdubois** [comment]
Yes of course, and we need to close https://github.com/jhipster/generator-jhipster/issues/5590 before doing the release -> I'm expecting this will take about 2 weeks to have everything clean

**Comment by JulienMrgrd** [comment]
(Knowing that I am actually migrating the Registry to Angular 4, based on a genetared Gateway in Angular 4 with the last generator, 4.2.0)

**Comment by deepu105** [comment]
Its done. And linting is enabled so build will fail when linting is wrong
