### ISSUE TITLE
Check that the Heroku button work with the current "develop" branch

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#125]
This can only be checked by @jkutner -> Joe, can you tell me when you can work on this? This will soon be a blocker issue for us, I'm sorry but I only thought of this now. @JulienMrgrd should be available to help you, you can ask him directly.

- This is to check https://elements.heroku.com/buttons/jhipster/jhipster-registry still works fine
- On our [develop branch](https://github.com/jhipster/jhipster-registry/tree/develop) we have migrated to Angular 4 -> this breaks the current system, as you need to run Yarn so the TypeScript code is compiled into JavaScript
- There are several ways to do this, but basically you can do: `yarn install && mvn` after checking out the project and it will work

**Comment by jkutner** [comment]
I will look at this today. We support Yarn, so i don't expect it to be a big deal.

**Comment by jkutner** [comment]
@jdubois i have it working, but the phantomjs tests are running, even when I have `-DskipTests`. Any idea how to skip those?

**Comment by jdubois** [comment]
@jkutner not sure they can be skipped at the moment.... `-DskipTests` is only for Maven, so Webpack is not aware of it. It's highly possible we change this build in the future, so the main point is that you have Webpack running - then the Webpack configuration might change, but your build will still be OK

**Comment by jdubois** [comment]
Closing as PR is merged
