### ISSUE TITLE
Empty home page after login

### ISSUE THREAD

**Issue by JulienMrgrd** [jhipster/jhipster-registry#130]
* _**develop branch**_

When you start the Regsitry (with yarn start) without a token, after sign in, you are redirected to a blank home page. If you refresh or quit/back the home page, it becomes complete.

![capture d ecran de 2017-05-03 10-01-13](https://cloud.githubusercontent.com/assets/11616517/25654070/0247a0da-2ff0-11e7-86ef-a9e49f34bd38.png)

* Trace 1 (empty home page)
-> (click on "sign in" button, in the modal, with admin/admin) 
-> login() function (in login.component.ts)
-> identity(), line 61 (principal.service.ts)
-> login() again
-> registerAuthenticationSuccess(), line 53 (home.component.ts)
-> login(), line 69, with ``redirect = null``

---------------------------------------------
* Trace 2 (completed home page)
-> (refresh or quit/back) 
-> canActivate() function (in user-route-access-service.ts)
-> the home component's ngOnInit
-> identity(), line 61
-> ngOnInit, inside "then" and populateDashboard() (home.component.ts) 
---------------------------------------------

We've to find a way to correctly init (by calling ngOnInit) the home component.
Any ideas ?

**Note** : Maybe related to jhipster/generator-jhipster#5658 and jhipster/generator-jhipster#5690

**EDIT** : And jhipster/generator-jhipster#5574

**Comment by jdubois** [comment]
Yes I had the same experience yesterday. We should also put there more information on Eureka/Config/Administration, like a small summary of each.

**Comment by jdubois** [comment]
Yes I had the same experience yesterday. We should also put there more information on Eureka/Config/Administration, like a small summary of each.

**Comment by ruddell** [comment]
I see the issue in the screenshot on a fresh Heroku deploy, it happens every login.

**username**: admin
**password**: tester
https://jhregistrytest.herokuapp.com/#/

**Comment by jdubois** [comment]
How do you do the deployment? Are you using the Heroku button?

**Comment by ruddell** [comment]
I used  https://dashboard.heroku.com/new?&template=https%3A%2F%2Fgithub.com%2Fjhipster%2Fjhipster-registry from the other issue

**Comment by JulienMrgrd** [comment]
As this issue is still present, I propose this patch, in home.component.ts :

```
this.principal.identity().then((account) => {
      this.account = account;
      this.populateDashboard();
});
```

(Note: related to jhipster/generator-jhipster#5574)
