### ISSUE TITLE
Some little fixes to bring before next release

### ISSUE THREAD

**Issue by JulienMrgrd** [jhipster/jhipster-registry#132]
- __On develop branch__

_(some of these fixes concerns eventually the generator too)_

- [ ] Footer always at the bottom of the page.
- [x] The Spring Cloud Configuration page : dropdown doesn't work and "404 Failed to load resource".
- [ ] The code-block color inside SSH page.
- [ ] In the Sign-in modal : "Sign in" text duplicated and unavailable links ("Did you forget your password?", "You don't have an account yet? Register a new account").
- [ ] And the most important, the issue #130

**EDIT :**
- [x] The @jdubois issue :arrow_down:

**Comment by jdubois** [comment]
I have another one: in the new "refresh" dropdown list, I have the instances always marked in red as "started".
<img width="781" alt="screenshot 2017-05-04 21 21 22" src="https://cloud.githubusercontent.com/assets/316835/25721148/bacf9a3e-310f-11e7-89f5-fafb8f3dd353.png">

**Comment by JulienMrgrd** [comment]
During the dev of this component and my tests, I've never seen any of my instances with a "Starting" status. 
I'll check now for your issue @jdubois.

**Comment by jdubois** [comment]
Yes I think that's because I clicked on it while the the services where starting. The label is probably not refreshed.
