### ISSUE TITLE
Microservice shows status down, with no errors

### ISSUE THREAD

**Issue by varunnmiglani** [jhipster/jhipster-registry#134]
I have created an microservice app using jhipster.

1. used jhipster registry.
2. used jhipster uaa.
3. created gateway using jhipster.

I have created microservice app with gradle and when I add 
compile "org.apache.solr:solr-solrj:5.4.1" this dependency, the app registers with status DOWN to registry and if I remove it, it registers with status UP and no errors are shown on the console.

Steps to reproduce:
1. use jhipster registry.
2. use jhipster uaa service.
3. create a microservice app with No DB and using jhipster registry + uaa server.
4. Simply add compile "org.apache.solr:solr-solrj:5.4.1" dependency to build.gradle file.

Please suggest

**Comment by jdubois** [comment]
We need your version numbers, etc....

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by jdubois** [comment]
Oh, and that's not a JHipster Registry bug?? I don't understand

**Comment by varunnmiglani** [comment]
Thanks for the quick reply though.

**Comment by jdubois** [comment]
@varunnmiglani oh sorry, I'm just reading this quickly: if your app depends on a service which is down, then Spring Cloud considers your app is down. So that looks quite logical to me.

**Comment by jdubois** [comment]
Then we don't support Solr, so that's hardly a bug on our side -> you should go to Stackoverflow, we're there too, but that's for questions (here you are on the bug tracker)

**Comment by varunnmiglani** [comment]
@jdubois Thanks, I will try my luck on Stackoverflow, have a great day.

**Comment by hana-ch** [comment]
varunnmiglani  hi ... i have the same problem ... can you tell me how do you solve it ??

**Comment by varunnmiglani** [comment]
Hi,

You need to configure solr properly, it fails to register if there is any
exception while auto configuring any library on the classpath like in your
case solr.
