### ISSUE TITLE
Password can't be modified with Heroku

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#135]
This is in the current master, that has just been merged with the changes for JHipster Registry v3.0.0.

This might not be limited to Heroku, but that's what I have tested so far -> @jkutner this is why I'm affecting the issue to you, but that might not be on your side, don't hesitate to tell it (and I'll test this again in the next few days).

When the JHipster password is changed to something else than `admin` in the Heroku screen when going to https://dashboard.heroku.com/new?&template=https%3A%2F%2Fgithub.com%2Fjhipster%2Fjhipster-registry , it is not possible to log in anymore.

I guess we have 2 variables here, and they are in conflict. This is an issue in the `application-*.yml` or `bootstrap-*.yml` files, probably.

So at the moment only the `admin` works.

**Comment by deepu105** [comment]
We need to fix this before release I guess? As it could be a security issue

**Comment by jdubois** [comment]
Well, I already did the release :-)
I didn't have time to check the issue in detail, unfortunately. There isn't a security issue (you can't log in), it's a more that you cant' use the app.
No problem in dev mode or with Docker Swarm, this is a usability issue for people using JHipster in the cloud. I'm pretty sure it's a Spring Boot property that needs to get overriden, nothing complex.

**Comment by jkutner** [comment]
In `Procfile` we override two values with the `JHIPSTER_PASSWORD`: 

```
--security.user.password=${JHIPSTER_PASSWORD:-"password"} --eureka.password=${JHIPSTER_PASSWORD:-"password"}
```

Maybe we need to override something from the `bootstrap-*.yml`? Also, values in the command line (i.e. the `Procfile`) take higher precedence. We could move these to a yml config file if we want them to have the same precedence.

In any case, it's not a security issue--only a bug. But I don't understand what's happening. I'll investigate.

**Comment by ruddell** [comment]
I've seen this in the past, it was because I was using a password less than 5 characters in length.  The Heroku Create page mentions that restriction but the length is not enforced.  I could log in after I changed the password to longer than 5 characters in the Heroku Settings

I was able to use the link from the first post and create a registry that works
**username**: admin
**password**: tester
https://jhregistrytest.herokuapp.com/#/

**Comment by jkutner** [comment]
@jdubois i haven't been able to reproduce this with a password longer than 5 chars. I think @ruddell's analysis is correct. Do you have any more details?

Do Docker or dev mode allow shorter passwords?

**Comment by jdubois** [comment]
I think we validate this on the server side, so that would be our fault - I'll have a look to remove that check

**Comment by jdubois** [comment]
I confirm this, the password should be more than 5 chars.
This is probably because we validate this, let me fix this (I should be
able to work on this tomorrow)

Le 9 mai 2017 3:16 PM, "Joe Kutner" <notifications@github.com> a écrit :

@jdubois <https://github.com/jdubois> i haven't been able to reproduce this
with a password longer than 5 chars. I think @ruddell
<https://github.com/ruddell>'s analysis is correct. Do you have any more
details?

Do Docker or dev mode allow shorter passwords?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-registry/issues/135#issuecomment-300159630>,
or mute the thread
