### ISSUE TITLE
Empty page after running registery with maven  

### ISSUE THREAD

**Issue by alialrabi** [jhipster/jhipster-registry#137]
I have clone jhipster registry and trying to deploy with maven ,I get no error ,but when going to lacalhost:8761 I get empty page..

   
![screenshot from 2017-05-11 13-00-55](https://cloud.githubusercontent.com/assets/7685208/25946092/e628af10-3649-11e7-87f2-77669b9a41e3.png)

Gateway get empty page too
 
  
![screenshot from 2017-05-11 13-04-16](https://cloud.githubusercontent.com/assets/7685208/25946208/5fc60a98-364a-11e7-8ea0-404b0d61b15b.png)

**Comment by jdubois** [comment]
Please read https://jhipster.github.io/jhipster-registry/ first

And next, time follow https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by alialrabi** [comment]
I have read this before submit issue,It didn't help

**Comment by jdubois** [comment]
Read again the part "Building from source".
Then it also depends on your version, that's why you should follow https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by jdubois** [comment]
We'll improve this in the next version, I understand this is not obvious for many people
