### ISSUE TITLE
User interface empty for v3.0.0, dev profile

### ISSUE THREAD

**Issue by dapperdanman** [jhipster/jhipster-registry#139]
I just cloned the jhipster-registry project, built it using the "dev" profile, launched the application using the dev,native profiles, and when I hit the URL http://127.0.0.1:8761 the website is empty. No content. No errors. 

If I checkout v2.6.0, everything looks good. 

I don't see any errors in the console.

**Comment by jdubois** [comment]
Yes, read the documentation, you need to run Yarn or do a prod build.

**Comment by dapperdanman** [comment]
It looks like the prod build needs yarn? I installed yarn, but the build won't work with Maven 3.0.4, it says it needs >3.1.0. 

Is there a pre-built binary distribution somewhere?

**Comment by jdubois** [comment]
Yes, you need Yarn to build the front end, and you should use the included Maven wrapper if you don't want to upgrade your Maven version (and sorry, we can't support all older versions).
You can also use the Docker image, or the Heroku button, if that's too complex

**Comment by jdubois** [comment]
This is a duplicate from #137

And as I said there, we'll improve this in the next release, I understand this isn't obvious.

**Comment by dapperdanman** [comment]
FYI, I'm in a corporate environment where I use an internal Nexus repository and have proxy issues to deal with. I've setup all that stuff in our normal Maven install, but the Maven wrapper doesn't honor those settings. There are open feature requests on that project for this issue. 

I'll work on getting our Maven upgraded, but I just wanted you to understand the motivation for why it isn't always simple to upgrade Maven (but it can be done)

**Comment by jdubois** [comment]
The motivation is just that we can't support everything, remember this is all done for free... Our recommended method is to use the Maven wrapper, which we do upgrade and test - and if you go outside that path, then you're on your own. It's probably going to work, it's just that we have better things to do in our free time, and so we're not spending time on this.
