### ISSUE TITLE
Distribute the registry as an executable JAR file

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#140]
Following #137 and #139 we should have a packaged release, that is easy to use, and not force people to build the app from the source.
We already distribute it as a Docker image, but not everyone uses Docker, of course.

Now, the easiest package would be an executable JAR (WAR?) file, but the problem is how can we distribute it:

- As a release on GitHub: that's easy to do, but we have no download stats, and that's a manual process
- On Maven Central? Like the way we already distribute the JHipster server lib: that would be more consistent, more secured (you need to sign it), and we would have download stats, but it's a bit more complex to set up

-> I'll try the second option, but if that's annoying I'll do the first one

**Comment by jdubois** [comment]
The second option is just too complex, I going with the first one, the release is under way.

**Comment by pascalgrimaud** [comment]
@jdubois : can you look this badge ? https://img.shields.io/github/downloads/jhipster/jhipster-registry/latest/total.svg
The download was 0. I just launch one, in the train, and now it's at 1 download
So does it work ?

**Comment by jdubois** [comment]
It should work, GitHub provides a REST API for this.

Le 15 mai 2017 7:16 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :
