### ISSUE TITLE
Refresh issues

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-registry#144]
In v3.0.1 there are few glitches.

When auto refresh is set on Instances it resets the tab selection and page reloads. the tab state should be preserved.

In the app route selector some services are always shown as starting though they are green
![image](https://cloud.githubusercontent.com/assets/1107223/26128782/eb410c48-3a8d-11e7-95d5-eedb3239d3c8.png)

ping @JulienMrgrd

**Comment by JulienMrgrd** [comment]
I will take a look.

**Comment by jdubois** [comment]
I don't have any issues at the moment
