### ISSUE TITLE
npm run ngc fails

### ISSUE THREAD

**Issue by liyakhatalikhan** [jhipster/jhipster-registry#145]
[WARNING ->]<template ngbModalContainer></template>
"): ng:///c:/work/jose/jhipster-ang4/src/main/webapp/app/layouts/footer/f
ooter.component.html@60:0
Error: Internal error: unknown identifier {}
    at _TsEmitterVisitor._resolveStaticSymbol (c:\work\jose\jhipster-ang4
\node_modules\@angular\compiler\bundles\compiler.umd.js:19014:19)
    at _TsEmitterVisitor._visitIdentifier (c:\work\jose\jhipster-ang4\nod
e_modules\@angular\compiler\bundles\compiler.umd.js:19032:23)
    at _TsEmitterVisitor.visitExternalExpr (c:\work\jose\jhipster-ang4\no
de_modules\@angular\compiler\bundles\compiler.umd.js:18694:14)
    at ExternalExpr.visitExpression (c:\work\jose\jhipster-ang4\node_modu
les\@angular\compiler\bundles\compiler.umd.js:15906:24)
    at _TsEmitterVisitor.AbstractEmitterVisitor.visitBinaryOperatorExpr (c:\work
\jose\jhipster-ang4\node_modules\@angular\compiler\bundles\compiler.umd.j
s:18385:17)
    at BinaryOperatorExpr.visitExpression (c:\work\jose\jhipster-ang4\nod
e_modules\@angular\compiler\bundles\compiler.umd.js:16047:24)
    at _TsEmitterVisitor.AbstractEmitterVisitor.visitIfStmt (c:\work\jose\mobil
e-hipster-ang2\node_modules\@angular\compiler\bundles\compiler.umd.js:18072:24)
    at IfStmt.visitStatement (c:\work\jose\jhipster-ang4\node_modules\@an
gular\compiler\bundles\compiler.umd.js:16456:24)
    at c:\work\jose\jhipster-ang4\node_modules\@angular\compiler\bundles\
compiler.umd.js:18495:58
    at Array.forEach (native)
Compilation failed

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jose\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ngc"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@1.0.0 ngc: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp@1.0.0 ngc script 'ngc -p tsconfig-aot.json'
.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myapp package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p tsconfig-aot.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jose\AppData\Roaming\npm-cache\_logs\2017-05-18T18_06_24_
443Z-debug.log

**Comment by deepu105** [comment]
Can you try with the node LTS version
