### ISSUE TITLE
Encrypt/decrypt endpoints are missing

### ISSUE THREAD

**Issue by abshkd** [jhipster/jhipster-registry#149]
I enabled the bootstrap setting `encrypt.key` for symmetric key encryption and I know it works on my system with Spring Boot `1.5.x` . However on JHipster 4.2 generated registry the endpoint does not get enabled and it returns a 404.
If there is another way or kind of encryption (asymmetric) that is being used, it is not documented. please advise.

Using jhipster-registry 3.0.1

**Comment by jdubois** [comment]
We're not doing anything specific here. In fact I've never configured those endpoints and I have no idea how they work.
You should ask this on Stackoverflow - all I can tell you is that there is nothing specific here.

**Comment by abshkd** [comment]
Thank you for that. I will look for answers elsewhere.

**Comment by ruddell** [comment]
I haven't tested this because I don't know exactly what you are doing, but Spring Boot management endpoints are all under the `/management` context-path (set in application.yml) so I would try `/management/encrypt` and `/management/decrypt`

https://github.com/jhipster/generator-jhipster/issues/3550

**Comment by jdubois** [comment]
Oh yes +1 @ruddell

**Comment by abshkd** [comment]
I am sorry the endpoints just doesn't exist and whatever you're saying may be correct to some extent.

Basically I do `curl http://localhost:8761/management/encrypt -d mysecret` and it returns 404.
Even with authorization header it wont work and return 404. 
However using the `management/refresh` endpoint it works with same authorization. 

I imagine this might be something to do with configuration not picking up `encrypt.key` value so I set the environment variable `ENCRYPT_KEY`. the endpoint sonly get enabled when the key is being read. As far as I can tell key is configured every possible way. I am not sure how this can go to production without a encrypting all the values in production. Please refer to this 
https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html under `Key management`
appreciate it.

**Comment by PierreBesson** [comment]
@abshkd I agree with you that this should work. Ideally we should even have an UI to encrypt decrypt keys and help setting up encryption. Would you be interested in contributing this feature ?

**Comment by ruddell** [comment]
@abshkd I solved this by checking the listing all RequestMappings, located at  `/management/mappings`.   This shows the encrypt and decrypt endpoints use the Config Server's prefix of `/config` (which is set in bootstrap.yml).  So they are located at `/config/encrypt` and `/config/decrypt`

I also verified they work as expected (after installing the prerequisite "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files").

**Comment by jdubois** [comment]
Oh yes @ruddell you are right, of course! So that's just the normal endpoints, in fact :-)
For JCE we have an issue: I don't think we can package this into our Docker image, for legal reasons of course

**Comment by PierreBesson** [comment]
@jdubois as we are using openjdk for our docker image I think we won't have any problem to use encryption features. Still I will do some testing...

**Comment by jdubois** [comment]
@PierreBesson it's a legal issue. You can't use "strong cryptography" in some countries - that includes Cuba (where there is a JHipster User Group getting set up!!) and Iran (where I had some great feedback from people working with JHipster on government projects!).
So maybe we should propose 2 Docker images, one with strong cryptography, and one without.

**Comment by abshkd** [comment]
@PierreBesson The UI is the whole reason I use JHipster because I suck at it :rofl: But hey why not, once I get a bit more comfortable with JHipster i will gladly send PR. 

Thanks for clarifying @ruddell I will test on `/config` and I am also deploying to heroku. That i can document.

@jdubois @PierreBesson Yes you can use encryption features with openjdk. **Do not package JCE**, JCE is specifically by Oracle and you cannot ship it. If someone wants to use JCE all we need is to document it on how to go about it. However I have seen a` buildpack` on Heroku that will download JCE automatically when the flag is `explicitly` set to true. Which to me is a very safe and sound way to go about enabling JCE support.


Thanks a lot folks, really appreciate so much support! I will definitely be contributing back if we get to go ahead with JHipster @work

**Comment by abshkd** [comment]
Works perfectly on heroku. used the buildpack https://elements.heroku.com/buildpacks/trautonen/heroku-buildpack-oracle-java here to enable JCE. I will send PR for documentation within the day.
