### ISSUE TITLE
[Security] anonymous access to configs possible through Direct object reference

### ISSUE THREAD

**Issue by abshkd** [jhipster/jhipster-registry#150]
After adding the `password` field to bootstrap.yml we are still able to access the configuration directly via the config path.
for e.g. `/config/APPNAME/PROFILE/LABEL` allows access to the configuration even though on the portal we are not logged in.

**Comment by PierreBesson** [comment]
I confirm the issue, doing a `curl http://localhost:8761/config/master/application-prod.yml` let's you get the configuration even though we are not authenticated.
This is strange, even though we do everything explained here about basic auth: https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_security and `/config/**` is covered by our spring security config.
ping @jdubois

**Comment by abshkd** [comment]
I am going to try vanilla spring boot, see if this issue exists. I do find
it hard to believe they would overlook such a thing.

**Comment by jdubois** [comment]
I confirm the issue, and I see why and it's really awful

**Comment by jdubois** [comment]
So this is because of line https://github.com/jhipster/jhipster-registry/blob/v3.0.1/src/main/java/io/github/jhipster/registry/config/SecurityConfiguration.java#L61

I think this was done because of refresh issues with the new UI, ping @JulienMrgrd

- I'm having a look at the issue this was supposed to solve
- I'll do a release to correct this

**Comment by jdubois** [comment]
And thanks a lot @abshkd !!!!

**Comment by abshkd** [comment]
@jdubois Yes, I saw that line too but my confidence is limited to point to
any code, sorry for that. I really appreciate the prompt response on this.
thank you!

**Comment by jdubois** [comment]
I'm doing some tests before doing a release, should be out soon.

**Comment by abshkd** [comment]
Is this resolved with tests? thanks

**Comment by pascalgrimaud** [comment]
@abshkd : it should be resolved in this last release. Can you try and confirm ?

**Comment by abshkd** [comment]
Yes. i can confirm. I am given a 404 error even if pre-authenticated. Which is as expected. Only way to access is to authenticate at request time. perfect! thanks.
