### ISSUE TITLE
Unable to deploy modified version of jhipster-registry to Heroku

### ISSUE THREAD

**Issue by nagarajasr** [jhipster/jhipster-registry#151]
I'm trying to deploy a modified version of JHipster-registry to Heroku. At the moment, the changes are very limited, e..g, a minor change in the app name in index.html. But no matter what method i try i'm unsuccessful to get it working on Heroku.
note: deploy stock JHipster registry using the Heroku button works fine.
Here's basically what i've tried, with a few variations (like using a slug)
Create an app on Heroku, add NodeJS and Java buildpacks and push local clone of github.com/jhipster/jhipster-registry with my changes. Env vars set as in app.json
in the most recent attempt, i got the app configured to listen on 8761 (earlier it used to pick a random port) but then fails to bind to 8761 and crashes
has anyone tried to deploy a modified version of jhipster-registry to heroku and how did you do it?
thanks in advance...

**Comment by jdubois** [comment]
Are you deploying it with "jhipster heroku"? I don't even know if that works... That's why we have the button :-)

**Comment by nagarajasr** [comment]
btw, this worked. sorry.

using heroku cli:

```heroku apps:create my-registry
heroku git:clone 
cd my-registry
git remote add origin https://github.com/jhipster/jhipster-registry
git pull origin master
vi src/main/webapp/index.html 
git add src/main/webapp/index.html 
git commit -m "updated name"
git push heroku master
```
this kicks off a build that ends with 
```
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 211.8M
remote: -----> Launching...
remote:        Released v7
remote:        https://my-registry.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/my-registry.git
 * [new branch]      master -> master
```
