### ISSUE TITLE
Minor issues with refresh

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#152]
Some minor IHM issues:

**1st issue** :
- go to Eureka > Instances
- select another microservice (another than the 1st microservice)
- activate refresh to 5sec
- after 5sec, the refresh forces the selection back to the 1st microservice
- the selection should stay with the selected microservice

**2nd issue** :
- go to Eureka > History
- select 'Last canceled leases'
- activate refresh to 5sec 
- the result list is back to 'Last registered leases', although 'Last canceled leased' is selected

**3rd issue** :
- go to Eureka > History
- the list is not corrected ordered by 'time'

cc @JulienMrgrd as you coded this part.
No worry, I can have a look later, and try to fix them

**Comment by deepu105** [comment]
Yes I had the same issue and opened a ticket earlier for that I guess


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I'm starting to fix these issues

**Comment by jdubois** [comment]
Great :-)

**Comment by pascalgrimaud** [comment]
Closing this ticket, it has been merged into develop branch
