### ISSUE TITLE
Configuration page use git has not 'Git Label'

### ISSUE THREAD

**Issue by saleson** [jhipster/jhipster-registry#153]
in the config.component.html and at 21 line, code is 
`<div class="form-group" *ngIf="isNative">
            <label for="label"><strong>Git Label: </strong></label>
            <input type="text" class="form-control" id="label" name="label" [(ngModel)]="label" required>
</div>`

is error?
why show the Git Label when isNative==true?

**Comment by PierreBesson** [comment]
Good catch @saleson
That should be `!isNative` as the `native` profile refer to loading configuration from the filesystem as opposed to loading configuration from git which is the default for the config server. @JulienMrgrd can you do the change ?

**Comment by JulienMrgrd** [comment]
Yes :)
