### ISSUE TITLE
The war package with Undertow doesn't work

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#16]
It seems `mvn package && java -jar target/*.war` with Undertow doesn't work on Linux, although it should be. I don't know if it's related to https://github.com/jhipster/generator-jhipster/issues/2948

Maybe we should stay with Tomcat ?

**Comment by jdubois** [comment]
Yes -> anyway it will have the same app server as the generator, and it seems like we are going to switch everything back to Tomcat

**Comment by pascalgrimaud** [comment]
Close via https://github.com/jhipster/jhipster-registry/commit/b72fc189705f12337eb4a3e55eec57a98e149f31
