### ISSUE TITLE
Cannot build registry on Macbook

### ISSUE THREAD

**Issue by GrowMon** [jhipster/jhipster-registry#162]
I've pulled down the latest code off of the master branch and when I try to package the application, the maven build process hangs.

**Steps to reproduce:**

1) Pull down the latest code from GitHub
2) (I have Maven 3.3.9) mvn clean package -Pprod, or use mvnw

**Expected Results:**
Artifact is generated.

**Actual Results:**

Process hangs, here is the output:
[INFO] Child html-webpack-plugin for "index.html":
[INFO]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 955 bytes {0} [built]

I have a Macbook Pro using Sierra V 10.12.5. I do not have Yarn installed and the Maven build is downloading and installing Yarn.

**Comment by jdubois** [comment]
I'm using this all the time, so I can guarantee that it works. Please note that we provide packaged version (WAR file, Docker image) so you don't need to do this if you are not developing anything.

What you should try:

- Delete your `node_modules` folder
- Install Yarn locally and run `yarn install` -> anyway you will need Yarn if you want to develop on the project
