### ISSUE TITLE
Feature: add admin page to view logfile

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#164]
##### **Description**

Currently, on my project (with @PierreBesson), sometimes, we need to check the logs of a specific microservice.
We could use ELK of course, but it should be interesting to have a page in jhipster-registry, similar to the pages Metrics, Configuration, etc.

##### **Solution**

So we will propose to use the API `management/logfile` provided by Spring Boot Actuator. Here the [doc](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)

##### **Screenshot**

![jhipster-registry-logfile](https://user-images.githubusercontent.com/9156882/28281665-2c2dbf4c-6b28-11e7-95ae-9084457b00be.png)

_____

So, what do you think?
If you're OK, I will push to a specific branch, so @PierreBesson can help to finish it.

**Comment by jdubois** [comment]
Doing some sort of "automatic scrolling" for a log file is complicated... What exactly have you got in mind:

- Sending the log to some kind of memory buffer, and printing it on screen
- Doing some kind of `tail -f` on `var/log/syslog` (but this will be OS-dependant)

**Comment by deepu105** [comment]
Awesome. @jdubois I think this should be good enough with the refresh settings :)

**Comment by jdubois** [comment]
OK, I didn't know this - no problem then!

**Comment by PierreBesson** [comment]
I think we should do polling on the /logfile endpoint.
From the actuator docs :
```
logfile | Returns the contents of the logfile (if logging.file or logging.path properties have been set). Supports the use of the HTTP Range header to retrieve part of the log file’s content.
```
We can then specify the Range header like this : `Range: bytes <currentByteCount>-` to request only new lines. It's not optimal but it should work.

**Comment by pascalgrimaud** [comment]
@PierreBesson : here the branch https://github.com/jhipster/jhipster-registry/tree/logfile

**Comment by PierreBesson** [comment]
Done in https://github.com/jhipster/jhipster-registry/pull/168. Hacking with Range headers doesn't seem too useful as we realized that this endpoint doesn't even show the full log (only recent lines).
