### ISSUE TITLE
gateway can not connect microservice

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-registry#170]
i insert vmware in my pc ,it create 2 Network Interfaces before the default Network Interfaces.  

gateway , jhipster-registry and uaa on othre machine.

i modify my application.yml by [Dalston.SR2/#ignore-network-interfaces](http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#ignore-network-interfaces)

myservice's applicaton.yml
```yml
#...
spring:
    cloud:
        inetutils:
          ignoredInterfaces:
            - VMware.*
#...
```
and run it.

output
```
----------------------------------------------------------
	Application 'xxx' is running! Access URLs:
	Local: 		http://localhost:8082
	External: 	http://172.60.30.14:8082
	Profile(s): 	[swagger, dev]
----------------------------------------------------------
```

but in the jhipster-registry Instances tab ,i got `192.168.17.1:8082`

![snipaste20170804_114810](https://user-images.githubusercontent.com/15098916/28953840-9610579c-790d-11e7-9c6e-3dc20f65cb38.png)

if i disabled the VMware.* Network Interfaces ,my service return to normal
![snipaste20170804_120938](https://user-images.githubusercontent.com/15098916/28953893-e40c21e2-790d-11e7-84a5-09efe7b13a6a.png)

![snipaste20170804_114727](https://user-images.githubusercontent.com/15098916/28953885-de8ccf6e-790d-11e7-9612-66f638507716.png)

myservice's applicaton.yml
```
eureka.instance.prefer-ip-address = false
eureka.instance.ip-address:172.60.30.14
```
this is invalid too.

os version : windows 10 version 1703
jhipster-registry version: v3.0.0
gateway,microservice,uaa version: 4.4.1
java version: 1.8.0_121
nodejs version: v7.7.2
yarn version: v0.23.4

**Comment by jdubois** [comment]
I'm sorry but questions on configuring VMWare are not bugs... We don't even support VMWare !
Please use Stackoverflow for configuration questions.

**Comment by anjia0532** [comment]
@jdubois this questions has nothing to do with vmware . why the setting ip-address or ignore ignore-network-interfaces it's invalid.

**Comment by jdubois** [comment]
Then can you send your full JHipster configuration, so we can test this without VMWare - but I'm pretty sure this works, we have tons of people using this

**Comment by jdubois** [comment]
We need to be able to reproduce

**Comment by anjia0532** [comment]
ok thanks for your reply. i'll upload demo to reproduce this

**Comment by PierreBesson** [comment]
@anjia0532 Note that we are currently using DALSTON.RELEASE for the registry and not the latest DALSTON.SR2, so maybe this is the problem...
I'm not familliar with this `ignoredInterfaces` feature and it seems that it's a recent addition. It's also not a priority of JHipster to support this.

**Comment by jdubois** [comment]
OK then I'm keeping this closed: if you modify the libraries versions, then we can't help you (we spend a lot of time testing this)

**Comment by anjia0532** [comment]
It's not about eureka or jhipster-registry . It could be a cache problem .

env:



|               type               |          value          |
|----------------------------------|-------------------------|
| os version                       | windows 10 version 1703 |
| jhipster-registry version        | v3.0.0                  |
| gateway,microservice,uaa version | 4.4.1                   |
| java version                     | 1.8.0_121               |
| nodejs version                   | v7.7.2                  |
| yarn version                     | v0.23.4                 |
| vmware ip                        | 192.168.17.1            |
| real ip                          | 172.60.30.14            |

step:

1. install [vmware](https://www.vmware.com/go/tryworkstation-win-cn) or [npcap](https://nmap.org/npcap/) for microserver's machine,you'll get vmware*  Network Interfaces  or Npcap  Network Interfaces .

2. running jhipster-registry,uaa,gateway on the other machine.

3. enabled all of the Network Interfaces. ensure vmware Network Interfaces is default.

4. run the microservice and open http://ip:8761/#/applications, the microservice' url like `http://192.168.17.1:8081/` 

5. keep running, modify myservice's applicaton.yml add `spring.cloud.inetutils.ignoredInterfaces:`
    ```
    #...
    spring:
        cloud:
            inetutils:
              ignoredInterfaces:
                - VMware.*
    #...
    ```
6. restart microservice and open http://ip:8761/#/applications, microservice url 90% still be `http://192.168.17.1:8081/` (10% possibilities is `http://172.60.30.14:8081/`). but if you stoped microservice to wait for it unregistered from jhipster-registry and restart it,the url must be `http://172.60.30.14:8081/`

7. although the url is `http://172.60.30.14:8081/`,the `http://172.60.30.14:8081/management/env`'s `spring.cloud.client.ipAddress` still be `192.168.17.1` but it's do not affect usage effect
    ```javascript
      //...
        "springCloudClientHostInfo": {
            "spring.cloud.client.hostname": "xxx",
            "spring.cloud.client.ipAddress": "192.168.17.1"
        },
      //...
    ```

**Comment by anjia0532** [comment]
@jdubois @PierreBesson  the microservice 4.4.1 is use  `Dalston.RELEASE` (pom.xml `<spring-cloud.version>Dalston.RELEASE</spring-cloud.version>`). but i dont find the `Dalston.RELEASE` doc from `http://projects.spring.io/spring-cloud/`, I dont change spring cloud version ,it just doc's version.

**Comment by PierreBesson** [comment]
@anjia0532 the DALSTON.RELEASE docs is at http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/. I agree that the Spring docs versioning is not good (not as good as what I did for https://jhipster.github.io/documentation-archive/ :wink:).
To fix your issue, you can try to deploy your registry to a dedicated server. I'm sorry but we don't have the time to solve everyone's configuration problems.

**Comment by anjia0532** [comment]
yup , the jhipster's doc is very good.  : )  
I thought i solved this problem. thank's for your help.
