### ISSUE TITLE
yarn.lock Error

### ISSUE THREAD

**Issue by rifatdover** [jhipster/jhipster-registry#176]
If I delete yarn.lock file from repo and run yarn install it fails

**Comment by pascalgrimaud** [comment]
can you be more precise and put the error logs here ?

**Comment by PierreBesson** [comment]
@rifatdover node-sass issue ?

**Comment by rifatdover** [comment]
@pascalgrimaud Yes I will.
@PierreBesson Yes it is.

##### **Overview of the issue**

If I delete yarn.lock file from repo and run yarn install fails

##### **Logs for the error**

` yarn run webpack:build
yarn run v0.27.5
$ yarn run ngc && webpack --config webpack/webpack.vendor.js && webpack --config webpack/webpack.dev.js
Warning: Can't resolve all parameters for AlertService in /my-project-directory/node_modules/ng-jhipster/src/service/alert.service.d.ts: ([object Object], ?, [object Object]). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for InterceptableHttp in /my-project-directory/node_modules/ng-jhipster/src/interceptor/interceptable-http.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  <div class="card">
    [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
      <div role="tab" id="{{panel.id}}-header"
        "): ng:///my-project-directory/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4
Hash: 11d94d660899f6e16456
Version: webpack 2.3.3
Time: 3456ms
        Asset     Size  Chunks                    Chunk Names
vendor.dll.js  3.78 MB       0  [emitted]  [big]  vendor
   [1] ./~/@angular/core/@angular/core.es5.js 460 kB {0} [built]
   [7] ./~/@angular/common/@angular/common.es5.js 131 kB {0} [built]
  [13] ./~/@angular/forms/@angular/forms.es5.js 204 kB {0} [built]
  [23] ./~/@angular/platform-browser/@angular/platform-browser.es5.js 141 kB {0} [built]
  [32] ./~/@angular/http/@angular/http.es5.js 73.2 kB {0} [built]
  [80] ./~/@angular/compiler/@angular/compiler.es5.js 962 kB {0} [built]
  [81] ./~/rxjs/Rx.js 9.58 kB {0} [built]
 [197] ./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 6.09 kB {0} [built]
 [199] ./~/@ng-bootstrap/ng-bootstrap/index.js 4.55 kB {0} [built]
 [200] ./~/angular2-cookie/core.js 782 bytes {0} [built]
 [201] ./~/jquery/dist/jquery.js 268 kB {0} [built]
 [202] ./~/ng-jhipster/index.js 3.18 kB {0} [built]
 [203] ./~/ng2-webstorage/dist/app.js 2.96 kB {0} [built]
 [204] ./~/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js 17 kB {0} [built]
 [496] dll vendor 12 bytes {0} [built]
    + 482 hidden modules


ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss
Module build failed: TypeError: Invalid PostCSS Plugin found: [0]
    at /my-project-directory/node_modules/postcss-load-plugins/lib/plugins.js:32:17
    at Array.forEach (native)
    at plugins (/my-project-directory/node_modules/postcss-load-plugins/lib/plugins.js:21:15)
    at /my-project-directory/node_modules/postcss-load-config/index.js:64:18
 @ ./src/main/webapp/content/scss/vendor.scss 4:14-194
 @ ./src/main/webapp/app/vendor.ts
 @ dll vendor`

##### **Motivation for or Use Case**

Yarn lock file is an autogenerated file and should be unbounded to project

##### **Reproduce the error**

1. Clone jhipster-registry repository
2. Delete yarn.lock file. 
3. Run yarn install

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/4900

##### **JHipster Version(s)**

```
jhipster-registery@3.1.0 /my-project-directory/jhipster-registery
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
└── generator-jhipster@4.3.0 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "jhipsterVersion": "4.3.0",
    "baseName": "JHipsterRegistry",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "serverPort": "8761",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "useSass": true,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": false,
    "skipUserManagement": false,
    "clientPackageManager": "yarn",
    "clientFramework": "angular2"
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>





</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.10.1

node: v6.9.2

npm: 3.10.9

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.06.1-ce, build 874a737

docker-compose version 1.14.0, build c7bdf9e

**Comment by PierreBesson** [comment]
>Yarn lock file is an autogenerated file and should be unbounded to project

I don't agree with this statement, without the lock file the build is completely non deterministic. Some guy somewhere could upgrade a npm dependency and break everything.

Anyway, we should upgrade the registry to a more recent version of JHipster to update all angular dependencies.

**Comment by rifatdover** [comment]
@PierreBesson there is a file called packages.json to keep that determinacy. If the problem is some guys upgrade a npm dependency int he end he will delete or change yarn.lock file also???

**Comment by PierreBesson** [comment]
@rifatdover Some clarifications :

The package.json is insufficient to be truly deterministic and this is by design (to implement npm's view of semantic versioning), however the JHipster project has a specific policy on this : "Policy 4: use strict versions for third-party libraries" (http://www.jhipster.tech/policies/).

See the initial yarn announcement for technical details : https://code.facebook.com/posts/1840075619545360

>if some guys upgrade a npm dependency in the end he will delete or change yarn.lock file also???

Yes when changing the package.json, the developer should launch yarn on his computer and commit any changes of his `yarn.lock` file.

Hope this answer your questions.

**Comment by rifatdover** [comment]
Well after i did some research and reading i saw that this is a question for everyone. 
https://github.com/yarnpkg/yarn/issues/1583
https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for

And i see that if your project is an application (which is the current case) you should commit yarn.lock. But if it is library you should not.

**Comment by rifatdover** [comment]
In the end you are right @PierreBesson it should be commited +1

**Comment by huiqiangyang** [comment]
Who can tell me reason and how to resolve it? 
thx!

**Comment by pascalgrimaud** [comment]
You can read @PierreBesson's post, he explained the problem with details.

The problem comes from transitive dependencies, and not on our side. That's why keeping the yarn.lock is important.

But the master branch will change soon, as we migrated to Spring Boot 2 in develop branch.
