### ISSUE TITLE
My jhipster registry does not launch UAA instance

### ISSUE THREAD

**Issue by vleboulanger** [jhipster/jhipster-registry#177]
Hello,

I am newer with jhipster. A society developp a project for me and give instructions for installing technical environment and source code.

When I want to launch Uaa server, I have a message which display 

`jhipster-registry_1  |  Application 'jhipster-registry' is running! Access URLs:`
`jhipster-registry_1  |  Local:          http://localhost:8761`

If I launch URL "http://localhost:8761", I can log in with admin account, but the app UAA is not up.

find attach stacktrace
[trace_uaa.txt](https://github.com/jhipster/jhipster-registry/files/1276694/trace_uaa.txt)

The resultat is the same between Windows 10 and Mac Os

have you an idea? a solution please?

Thanks !

Vincent

**Comment by jdubois** [comment]
I'm sorry but this is the bug tracker... For general questions, please use StackOverflow using the JHipster tag

**Comment by vleboulanger** [comment]
Ok thanks, I have already do that

**Comment by jdubois** [comment]
@vleboulanger I just realized this is not clear, I'm adding a CONTRIBUTING.md file to help, I will link it here

**Comment by jdubois** [comment]
@vleboulanger oh, then please don't cross post between the bug tracker and StackOverflow, this just confuses people. The good place is StackOverflow, it's easier to search, tag, vote... The bug tracker is just too limited for questions.

**Comment by vleboulanger** [comment]
@jdubois Ok, I understand.
Thank you!

**Comment by jdubois** [comment]
I just added contributing guidelines and help, see https://github.com/jhipster/jhipster-registry/commit/9cd1f224afb6bf035c8e782a02a690a8f974cbc0
