### ISSUE TITLE
version 3.1.1 uses native in prod profile

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/jhipster-registry#179]
##### **Overview of the issue**

When running the JHipster Registry in the `prod` profile as suggested in the documentation http://www.jhipster.tech/jhipster-registry/
```
./jhipster-registry-3.1.1.war` --spring.profiles.active=prod --security.user.password=admin --jhipster.security.authentication.jwt.secret=secret-key --spring.cloud.config.server.git.uri=https://github.com/jhipster/jhipster-registry-sample-config
```
then JHipster Registry is using Spring Cloud Config `native` profile:
```
        Profile(s):     [native, prod]
----------------------------------------------------------
```

##### **Motivation for or Use Case**

In prod profile I want to be able to use configuration from git. JHipster Registry documentation http://www.jhipster.tech/jhipster-registry/ supports this wish in prod profile.

##### **Reproduce the error**

Run
```
./jhipster-registry-3.1.1.war` --spring.profiles.active=prod --security.user.password=admin --jhipster.security.authentication.jwt.secret=secret-key --spring.cloud.config.server.git.uri=https://github.com/jhipster/jhipster-registry-sample-config
```

##### **Suggest a Fix**

Seems that this problem comes from this commit: https://github.com/jhipster/jhipster-registry/commit/55dc94856e1fd265001a5361d8a51bd8518d0211

Maybe create `bootstrap-dev.yml` and put
```
spring:
    profiles:
        include: native
```
into this new file.

##### **JHipster Registry Version(s)**

This problem exists in version 3.1.1.  
This problem doesn't exist in version 3.1.0

##### **Browsers and Operating System**

Tested both in Centos and Windows. Same behaviour.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
I updated report, in run commands changed JHipster Registry version from 3.1.0 (copy-paste from JHipster Registry documentation) to 3.1.1.

**Comment by jdubois** [comment]
Yes this looks like an error to me - @PierreBesson can you check? There is indeed a `git` profile in Spring Cloud Config, which is documented at http://www.jhipster.tech/jhipster-registry/#spring-cloud-config on our side
I can do a release this afternoon if needed

**Comment by kaidohallik** [comment]
Additional note about documentation. In this commit: https://github.com/jhipster/jhipster.github.io/commit/d8322244f3ab3f27ce9b4d8ed7fff4a36416e83b is said that set `jhipster.security.authentication.jwt.secret`, but in fact this should be loaded from the `central-config` directory in the `dev` profile and from the git repo https://github.com/jhipster/jhipster-registry-sample-config in the `prod` profile.

**Comment by jdubois** [comment]
Yes I need to review this part - @kaidohallik can you help? I'll probably do a release this afternoon, but my time is limited so help is really welcome

**Comment by kaidohallik** [comment]
I'm quite busy next couple of hours. Yesterday I tried to compile jhipster-registry with prod profile and it took very long so I couldn't wait while it ends. What is the normal run time of the `./mvnw -Pprod`?

**Comment by jdubois** [comment]
Should be a few minutes, but it really depends on your Internet connection
(there are some useless transitive dependencies that Yarn does not cache...)

Le 13 sept. 2017 8:48 AM, "Kaido Hallik" <notifications@github.com> a
écrit :

I'm quite busy next couple of hours. Yesterday I tried to compile
jhipster-registry with prod profile and it took very long so I couldn't
wait while it ends. What is the normal run time of the ./mvnw -Pprod?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-registry/issues/179#issuecomment-329075109>,
or mute the thread

**Comment by kaidohallik** [comment]
`mvnw -Pprod` was not completed after 4 hours of running. So I canceled build. I'm on Windows.  
Build stucked at this line:
```
[INFO] $ yarn run webpack:build
```

So I removed `com.github.eirslett.frontend-maven-plugin` from `prod` profile and ran:
```
yarn install
yarn run webpack:prod
mvnw -Pprod
```
Then application started successfully.

I tested solution I proposed and in my tests it worked successfully in all cases.  
I'm doing PR for that.

**Comment by jdubois** [comment]
So I reverted the commit in https://github.com/jhipster/jhipster-registry/commit/864cc860218b4c449a7cb2f9cc00427aff3f3904

**Comment by PierreBesson** [comment]
Yes, I think your reverting fixes it.
This code is confusing and I always come back to it and forget how it works. However the  `git` profile doesn't exist, the git config source being the default and doesn't need a profile to be activated.

**Comment by jdubois** [comment]
Oh @PierreBesson sorry about the `git` profile: it used to exist in Spring Cloud Config, do you mean they removed it? I need to check

**Comment by PierreBesson** [comment]
@jdubois It has never existed :smile: !
https://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.2.3.RELEASE/#_environment_repository
