### ISSUE TITLE
JHipster registry docker image doesn't work on OpenShift

### ISSUE THREAD

**Issue by hufon** [jhipster/jhipster-registry#189]
##### **Overview of the issue**

JHipster registry docker image (on DockerHub) needs to have root access.
It need to write in /target directory for logs.
This directory is not created in the dockerfile

##### **Motivation for or Use Case**

I need to maintain an override of image : 
`FROM jhipster/jhipster-registry:v3.1.2

RUN mkdir /target && chmod g+rwx /target

`

It's a bad pratice that docker image needs to be root...

##### **Reproduce the error**

Just deploy hipster/jhipster-registry on minishift

You'll get a "Could not write to /target/...." error

##### **Suggest a Fix**

Just add 
RUN mkdir /target && chmod g+rwx /target

In the https://hub.docker.com/r/jhipster/jhipster-registry/~/dockerfile/

##### **JHipster Registry Version(s)**
latest :  v3.1.2

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Did you use our Openshift sub-generator? I'm pretty sure it works, it's made by Red Hat

**Comment by hufon** [comment]
Yes i use it.
And when using it, (without touching anything else) jhipster registry refuse to start

![selection_095](https://user-images.githubusercontent.com/1788150/31533448-949e1108-aff2-11e7-8bcf-6011d66790d8.png)

**Comment by hufon** [comment]
The jhipster registry part is not running with the jhispter service account which has right for anyuid.
But if we modify the dockerfile as i suggested, all would be right!

**Comment by hufon** [comment]
The problem comes from this commit : https://github.com/jhipster/jhipster-registry/commit/085439b9c33c5a84746d39c473f1ec8c10b78a63#diff-285a2da9b966f929edc1374c522a0449

So, this is a regression, it use to work with 3.1.1

**Comment by pascalgrimaud** [comment]
Creating the `target` folder should be OK
@hufon : do you want to PR ?

**Comment by hufon** [comment]
Hi, i don't know where is the https://hub.docker.com/r/jhipster/jhipster-registry/~/dockerfile/ Dockerfile,
It's not the same as the one in https://github.com/jhipster/jhipster-registry/blob/master/src/main/docker/Dockerfile

**Comment by pascalgrimaud** [comment]
It's this file https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile in the root folder

**Comment by hufon** [comment]
Ah, ok, btw why two versions? 
I'll do the pull request

**Comment by pascalgrimaud** [comment]
The Dockerfile inside `src/main/docker` is used in development only.
For Docker Hub, it's the `Dockerfile` in the root folder which is used

**Comment by hufon** [comment]
PR done.

There's still another problem with environment variables like ${GIT_URI} not evaluated in this version of Dockerfiles (you've to create an entrypoint) but i will open a new issue if i have time...

**Comment by pascalgrimaud** [comment]
Thanks for PR, I will have a look when I have time

And yes, if you have another issue, plz open a new one, so it's clear

**Comment by jdubois** [comment]
Thanks @hufon for the bug report, the explanation, and the PR! You rock :-)

**Comment by hufon** [comment]
No, the bug is not fixed... 

```
docker run jhipster/jhipster-registry:master /bin/sh -c 'ls -la /target'
ls: /target: No such file or directory
```
apparently this dockerfile is used to compile and build the image and not for running

**Comment by PierreBesson** [comment]
@hufon Yes the lines were not added at the right place: the correct fix is:. https://github.com/jhipster/jhipster-registry/pull/192

**Comment by hufon** [comment]
I confirm it works!
Thanks!
