### ISSUE TITLE
frontend-maven-plugin makes hangs on Win 10

### ISSUE THREAD

**Issue by picolov** [jhipster/jhipster-registry#195]
##### **Overview of the issue**
process hangs when try running jhipster cloudfoundry

##### **Motivation for or Use Case**
cannot deploy to cloudfoundry because of this

##### **Reproduce the error**
1. git clone latest source
2. run jhipster cloudfoundry

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/5788

##### **Suggest a Fix**
update frontend-maven-plugin version to 1.6

##### **JHipster Registry Version(s)**
3.1.2 (latest)

##### **Browsers and Operating System**

Windows 10
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
- not sure the current master is stable, please test with a release
- which Cloud Foundry are you using? It greatly depends on the version & distribution

**Comment by picolov** [comment]
mvnw -Pprod also hangs, so not because the cloudfoundry, after i change frontend-maven-plugin version to 1.6 (following the solution on https://github.com/jhipster/generator-jhipster/issues/5788, same problem i believe), the problem is resolved.

**Comment by jdubois** [comment]
Oh OK then let's upgrade the plugin.

**Comment by jdubois** [comment]
Closing as PR is merged
