### ISSUE TITLE
The dockerfile dev profile do not pick local application.yml

### ISSUE THREAD

**Issue by Tcharl** [jhipster/jhipster-registry#196]
It looks like the Dockerfile in dev do not pick the local central-config file but try to grab it from github.
It's particularly problematic when being behind a proxy...

##### **Overview of the issue**

A nice stacktrace when doing docker-compose -f jhipster-registry up behind a corporate proxy with the jhipster generated file:

`docker-compose -f jhipster-registry.yml up
Starting docker_jhipster-registry_1
Attaching to docker_jhipster-registry_1
jhipster-registry_1  | 
jhipster-registry_1  |         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
jhipster-registry_1  |         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
jhipster-registry_1  |         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
jhipster-registry_1  |   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
jhipster-registry_1  |   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
jhipster-registry_1  |    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
jhipster-registry_1  | 
jhipster-registry_1  | :: JHipster Registry :: Running Spring Boot 1.5.4.RELEASE ::
jhipster-registry_1  | :: http://jhipster.github.io ::
jhipster-registry_1  | 
jhipster-registry_1  | 2017-10-23 09:59:24.159 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
jhipster-registry_1  | 
jhipster-registry_1  | java.lang.IllegalStateException: Cannot clone or checkout repository
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:203)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:155)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:132)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:42)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:170)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.EnvironmentRepositoryPropertySourceLocator.locate(EnvironmentRepositoryPropertySourceLocator.java:50)
jhipster-registry_1  |  at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:93)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
jhipster-registry_1  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
jhipster-registry_1  |  at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:75)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jhipster-registry_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jhipster-registry_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
jhipster-registry_1  |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
jhipster-registry_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
jhipster-registry_1  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
jhipster-registry_1  |  at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
jhipster-registry_1  | Caused by: org.eclipse.jgit.api.errors.TransportException: https://github.com/jhipster/jhipster-registry: cannot open git-upload-pack
jhipster-registry_1  |  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:135)
jhipster-registry_1  |  at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:203)
jhipster-registry_1  |  at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:136)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:402)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.copyRepository(JGitEnvironmentRepository.java:376)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.createGitClient(JGitEnvironmentRepository.java:361)
jhipster-registry_1  |  at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:177)
jhipster-registry_1  |  ... 18 common frames omitted
jhipster-registry_1  | Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/jhipster/jhipster-registry: cannot open git-upload-pack
jhipster-registry_1  |  at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:551)
jhipster-registry_1  |  at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:311)
jhipster-registry_1  |  at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
jhipster-registry_1  |  at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
jhipster-registry_1  |  at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1201)
jhipster-registry_1  |  at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
jhipster-registry_1  |  ... 24 common frames omitted
jhipster-registry_1  | Caused by: java.net.UnknownHostException: github.com
jhipster-registry_1  |  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
jhipster-registry_1  |  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
jhipster-registry_1  |  at java.net.Socket.connect(Socket.java:589)
jhipster-registry_1  |  at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
jhipster-registry_1  |  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
jhipster-registry_1  |  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
jhipster-registry_1  |  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
jhipster-registry_1  |  at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
jhipster-registry_1  |  at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
jhipster-registry_1  |  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
jhipster-registry_1  |  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
jhipster-registry_1  |  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
jhipster-registry_1  |  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
jhipster-registry_1  |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
jhipster-registry_1  |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
jhipster-registry_1  |  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
jhipster-registry_1  |  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
jhipster-registry_1  |  at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98)
jhipster-registry_1  |  at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:196)
jhipster-registry_1  |  at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:489)
jhipster-registry_1  |  ... 29 common frames omitted
`

##### **Motivation for or Use Case**

Ability to use jhipster-registry.yml compose file behind a proxy

##### **Reproduce the error**

Try to launch docker-compose up on the generated jhipster-registry.yml generated by jhipster

##### **Suggest a Fix**

Update the documentation to let the user add:
` - _JAVA_OPTIONS=-Dhttps.proxyHost=<proxy_host> -Dhttps.proxyPort=<proxy_port> -Dhttps.proxyUser=<proxy_user> -Dhttps.proxyPassword=<proxy_pwd> -Djdk.http.auth.tunelling.disabledScheme="" -Djdk.http.auth.proxying.disabledScheme=""`

To the compose file in order to get it work, also removing the comments in the jhipster-registry.yml file as it does not work (the jhipster-registry Dockerfile hasn't any operation to pick the local file)

##### **JHipster Registry Version(s)**

3.1.2 even master

##### **Browsers and Operating System**

any

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes by default it uses the "Git" config, if you want the filesystem config you need to use the "native" profile

**Comment by Tcharl** [comment]
Sorry, I should have had a prior version of the generation: mine said

# When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the configuration from a Git repository
        # See http://www.jhipster.tech/microservices-architecture/#registry_app_configuration


I did just checked the new template, everything is OK now ;-).

Thank you!

**Comment by 62mkv** [comment]
@jdubois: 
> if you want the filesystem config you need to use the "native" profile

And how do I do this ? `jhipster-registry.yml` file that I have within another microservice, has 
```
            - SPRING_PROFILES_ACTIVE=dev
```
line in it; should that use Git config as well ? 


@Tcharl 
> Update the documentation to let the user add: - _JAVA_OPTIONS=...

sorry, where should this be added ? into the `docker-compose ...up` command line ? 

Thx!

**Comment by 62mkv** [comment]
two more remarks: 
1) the `src/main/docker/jhipster-registry.yml` that I have says: 
```
        # When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
```
So, is (was) it a bug ? I mean, that while active profile is set to dev, it still grabs Cloud Config from Git.

it's generated with .. I don't know actually with which JHipster version, but it's committed on 20th of Oct, 2017. 

2) I've tried to put `export HTTPS_PROXY=http://zscaler.proxy.int.kn:80` into /home/docker/.ashrc file (using `docker-machine ssh`) and no changes, unfortunately. 

Question is: how do I run this JHipster Registry with Docker with a config read from file, not from Git? Or is the only option to achieve this to just clone the `jhipster-registry` repo and run it from there ?

**Comment by jdubois** [comment]
@62mkv  I just checked with the latest master (of course that depends on your release, and maybe you have a bug, but as you don't have the version, who knows...), and indeed it picks up the configuration in the `central-server-config` directory.

If you want to test easily (there are many other ways, of course):

- Git clone the repo
- Modify a property in the `central-config/application.yml`, like `configserver.name`
- Start the app with `./mvnw`
- If you want the front end, do a `yarn install && yarn start` (it's a typical JHipster app, here also there are other ways to do it, have a look at the JHipster documentation). With the front end there is a screen where you can see the config, so you should be able to see your change in `configserver.name` there.

Now with Docker you have several options. First of all everything can be configured using environment variables, as it's a Spring Boot application: you can change your Spring profile, change the folder where the config is stored, configure Git.... Now from a practical point of view I guess you can read stuff from the local filesystem, but with Docker it's usually a bit complex (you need to mount a volume, etc), so for me using Git is easier (not to mention you can commit/tag/rollback so it's far more powerful).

**Comment by 62mkv** [comment]
Thanks, @jdubois .. I will give it a try tomorrow in the workplace again. 

At home, I've just created empty new JHipster microservice and the very same command (docker-compose -f .. up) works *like a charm!* Of course, I don't have that corporate proxy at home, and also I use native Docker, not that old Docker Toolbox.

Ehhhh, old story..
