### ISSUE TITLE
Develop : OIDC session cookie conflict with the gateway

### ISSUE THREAD

**Issue by SebastienRene** [jhipster/jhipster-registry#200]
##### **Overview of the issue**
During **development** with OIDC support on microservices, using the JHipster-registry and a generated gateway , there are conflicts between the two applications : switching from one to another after login leads to a "You are logged in as user "anonymousUser". " message.
Since the authentication is statefull with OIDC, the JSESSIONID cookie is shared on localhost domain between the two applications. 

##### **Motivation for or Use Case**

During development, we should be able to switch between the registry and the gateway with no conflict on a single browser.

##### **Reproduce the error**

1. Launch Keycloak with docker-compose file from the registry.
2. The JHipster-registry is launch with the oauth2,native profile.
3. A gateway is generated and launched with OIDC support.
4. You login the registry, browser is redirected to the Keycloak's login page, you login in the IDP and go back the home page.
5. With a new tab, you login the gateway, no credentials are needed since SSO is activated.
6. You go back to the registry tab, refreshing the page leads to "You are logged in as user "anonymousUser" message

##### **Related issues**

Not found

##### **Suggest a Fix**

This issue is caused by a security context loss because the JSESSIONID cookie on localhost is overwritten when you login the second application.
I suggest to customize the cookie name in the registry with oauth2 profile with the property : server.session.cookie.name: JSESSIONID_REGISTRY
This fix has no impact on the generator.

##### **JHipster Registry Version(s)**

Registry v3.2.3

##### **Browsers and Operating System**

Ubuntu 17 (JHipster dev box)

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/vagrant/workspace/oauth/gateway
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.jhipster",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "fr.jhipster",
    "packageFolder": "fr/jhipster",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0

node: v8.7.0

npm: 5.5.1

bower: 1.8.2

gulp:
[15:21:31] CLI version 3.9.1

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.10.0-ce, build f4ffd25

docker-compose version 1.17.0-rc1, build a0f95af

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Oh yes I totally confirm the issue!

**Comment by pascalgrimaud** [comment]
Closing this, as the PR is merged into develop branch.
