### ISSUE TITLE
Error after importing into eclipse

### ISSUE THREAD

**Issue by pmverma** [jhipster/jhipster-registry#204]
##### **Error after importing into eclipse**

I have successfully imported this project in Eclipse.

However, after importing an error exists in `UserVMTest.java` saying `The type javax.servlet.ServletException cannot be resolved. It is indirectly referenced from required .class files`
I also do not see this exception declared anywhere in the code.

If I delete `UserVMTest.java`, error displaying in `LoginVMTest.java`.

##### **Motivation for or Use Case**
Importing the project into eclipse should be error free.

##### **Reproduce the error**

1. Import project into eclipse.
2. You will see error after import finish and build finish.

##### **Related issues**

-

##### **Suggest a Fix**

-

##### **JHipster Registry Version(s)**

v 3.2.3

##### **Browsers and Operating System**

Windows 10

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
No you didn't import the project successfully in Eclipse as the classpath is wrong.
It depends on how you import the project, you should do "import an existing Maven project".
This isn't a bug but a configuration issue, we should discuss this on StackOverflow.

**Comment by geoffroya** [comment]
I confirm @pmverma issue, on Eclipse Neon

**Comment by jdubois** [comment]
Are you sure you have correctly set up your JDK? I'm sorry but this is a configuration issue with your IDE, as long as it runs correctly with Maven.

**Comment by geoffroya** [comment]
I can confirm it runs well with other maven projects as I did this in my
current workspace, working with other maven projects

2017-11-28 13:38 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by mouadtk** [comment]
check if your installed JDK is a Java EE edition, not a SE.
