### ISSUE TITLE
yarn run webpack:dev error

### ISSUE THREAD

**Issue by asenguptagithublocalwi** [jhipster/jhipster-registry#206]
$ yarn run webpack:dev
$ webpack-dev-server --config webpack/webpack.dev.js  --progress --inline --hot --profile --port=9060
module.js:471
    throw err;
    ^

Error: Cannot find module '<Node installation>\node_modules\webpack-devserver\bin\webpack-devserver.js'

**Comment by jdubois** [comment]
You need to run `yarn install`
