### ISSUE TITLE
jhispter-registry latest pack problem

### ISSUE THREAD

**Issue by asenguptagithublocalwi** [jhipster/jhipster-registry#207]
I found jhipster-registry <latest pack> from github runs into a problem when started with .\mvnw on win-64. The whole package gets compiled, no error produced and shows:
Application 'jhipster-registry' is running! Access URLs:
        Local:          http://127.0.0.1:8761
        External:       http://192.168.99.1:8761
        Profile(s):     [native, dev]
but the http://127.0.0.1:8761 shows a blank page [IE + Chrome].
Got to know that the latest version has a problem from the list of chats; so replaced with v 2.6.0 and finally all run OK.

**Comment by jdubois** [comment]
That's probably because you didn't run `yarn start` (at least you don't talk about it)

**Comment by asenguptagithublocalwi** [comment]
Well, with due respect no, I didn't do that for v2.6.0 either, yet it runs.

**Comment by pascalgrimaud** [comment]
The version v2.6.0 was with AngularJS

Now, it's Angular so the workflow to use in dev has changed. You need to compile the front part.

**Comment by deepu105** [comment]
If you dont want to deal with it you could also use the webpack profile and run `../mvnw -Pdev,webpack`

**Comment by deepu105** [comment]
Btw this is clearly stated in docs. I'll also update the Readme to be clearer
