### ISSUE TITLE
Add prod environment variables to dockerfile

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#22]
Currently when running the registry with docker, only the `dev,native` profile is usable. Because it is not possible to specify the git uri for the configuration source.

I propose to add the following:
  - GIT_URI
  - GIT_SEARCH_PATH

And then pass them to the war as command line args.

We have already made the changes in the [docker-compose generator](https://github.com/jhipster/generator-jhipster-docker-compose/blob/master/generators/app/templates/_docker-compose.yml).
@pascalgrimaud is it OK for you. Or do you have a better solution ?

**Comment by pascalgrimaud** [comment]
Yes! playing with environment variables in docker-compose files is good
it's better than overriding the `command:` session

**Comment by PierreBesson** [comment]
Closing via #24
