### ISSUE TITLE
Why it doesn't support i18n?

### ISSUE THREAD

**Issue by yuedefeng** [jhipster/jhipster-registry#220]

**Comment by jdubois** [comment]
Too much work for us

**Comment by yuedefeng** [comment]
Maybe it is uniform to use i18n/en/global.json for Jhipster project.  If you do that, Other language people just need to translate global.json, Will it be supported by the follow version ?   Thanks.

**Comment by pascalgrimaud** [comment]
No one, from the core team, will do that, because it's too much work to maintain, and there are other priorities as React, Spring Boot 2 etc. 

You are free to fork the project and do it on your fork.

**Comment by PierreBesson** [comment]
I also think that there is little value to have different languages for the registry.
We already put a lot of work in this and provide this for free, so @yuedefeng need to understand why we are not too enthused to do it ourselves. But what you suggest (having i18n enabled with only english) is a not a bad idea, it will just give us more work.

**Comment by yuedefeng** [comment]
Thanks for your response.
