### ISSUE TITLE
Upgrade to Spring Cloud Edgware

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#222]
To align with the generator, the registry needs to use the same Spring Cloud version.

See: https://github.com/jhipster/generator-jhipster/issues/6755

**Comment by pascalgrimaud** [comment]
@PierreBesson : currently, we use `Finchley.M7` -> https://github.com/jhipster/jhipster-dependencies/blob/master/pom.xml#L95
And I did the upgrade in this PR https://github.com/jhipster/jhipster-registry/pull/248

So do you think we can close this ticket ?

**Comment by PierreBesson** [comment]
Yes only finchley is compatible with sb2 so we need to use it.
