### ISSUE TITLE
Remove usage of javax.xml.bind.DatatypeConverter (removed in Java 9)

### ISSUE THREAD

**Issue by amrsalem87** [jhipster/jhipster-registry#231]
##### **Overview of the issue**

We know this version might be not compatible with JDK 9 yet, just thought to bring this to your attention, for future releases.

Application throughs following exception if Java is set to version 9

2018-01-20 11:48:09.984 ERROR 5175 --- [ XNIO-2 task-14] i.g.j.r.aop.logging.LoggingAspect        : Exception in io.github.jhipster.registry.web.rest.UserJWTController.authorize() with cause = 'java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter' and exception = 'javax/xml/bind/DatatypeConverter'

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

##### **Motivation for or Use Case**

Upgrade to Java 9 

##### **Reproduce the error**

 run ./mvnw -Pprod using following Java version.

java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
##### **Suggest a Fix**

Remove usage of javax.xml.bind.DatatypeConverter (removed in Java 9)

##### **JHipster Registry Version(s)**

v3.2.4

##### **Browsers and Operating System**

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes it's a know issue with Spring Boot 2 + Java 9 -> I'm taking care of this in the main generator, so this will work here when we upgrade (please note Java 8 is the only LTS release at the moment, so we might not upgrade soon)
