### ISSUE TITLE
Could not access to /management/health when not logged

### ISSUE THREAD

**Issue by c-robin** [jhipster/jhipster-registry#233]
##### **Overview of the issue**

"Access denied" when using /management/health

##### **Motivation for or Use Case**

We would like to use /management/health to use it for an external monitoring tool (without being logged).
/management/health is open in [jhipster-sample-app](https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/config/SecurityConfiguration.java#L104)

##### **Reproduce the error**

clone the project, run it, go to localhost:8761/management/health

##### **Related issues**

I didn't find any.

##### **Suggest a Fix**

Will do a PR.

Edit: [PR#234](https://github.com/jhipster/jhipster-registry/pull/234)

##### **JHipster Registry Version(s)**

3.2.1, Not a regression

##### **Browsers and Operating System**

Linux, chromium-browser

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
It seems that Spring boot 2 introduce a new `/status` endoint which has less information than the /health endpoint : https://spring.io/blog/2017/09/15/security-changes-in-spring-boot-2-0-m4#status-endpoint
So we will move to this when we migrate the registry to SB 2 and require authentication for the health endpoint again as it does expose some potentially sensible info: 
```
{
  "description": "Spring Cloud Eureka Discovery Client",
  "status": "UP",
  "discoveryComposite": {
    "description": "Spring Cloud Eureka Discovery Client",
    "status": "UP",
    "discoveryClient": {
      "description": "Spring Cloud Eureka Discovery Client",
      "status": "UP",
      "services": [
        "app"
      ]
    },
    "eureka": {
      "description": "Remote status from Eureka server",
      "status": "UP",
      "applications": {
        "APP": 1,
      }
    }
  },
  "diskSpace": {
    "status": "UP",
    "total": 507170856960,
    "free": 201232957440,
    "threshold": 10485760
  },
  "refreshScope": {
    "status": "UP"
  },
  "hystrix": {
    "status": "UP"
  },
  "configServer": {
    "status": "UP",
    "repositories": [
      {
        "sources": [
          "file:****"
        ],
        "name": "app",
        "profiles": [
          "default"
        ],
        "label": null
      }
    ]
  }
}
```

**Comment by ruddell** [comment]
@PierreBesson @pascalgrimaud It only returns all of that information when authenticated.  When you are not authenticated, `/management/health` returns only the status:

```sh
 curl localhost:8761/management/health
{
  "description" : "Spring Cloud Eureka Discovery Client",
  "status" : "UP"
}
```
Authenticated:
```sh
 curl localhost:8761/management/health  -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTUxNjg5NDcwOX0.U9dhwQOi1vcZD5L5R-JNa5jOirbwaSK_Icd9WeHvPzaS6JSeLHq7sUKvM04C7dg07hS75Mh7qRIDLzOKfcbOOw'
{
  "description" : "Spring Cloud Eureka Discovery Client",
  "status" : "UP",
  "discoveryComposite" : {
    "description" : "Spring Cloud Eureka Discovery Client",
    "status" : "UP",
    "discoveryClient" : {
      "description" : "Spring Cloud Eureka Discovery Client",
      "status" : "UP",
      "services" : [ ]
    },
    "eureka" : {
      "description" : "Remote status from Eureka server",
      "status" : "UNKNOWN",
      "applications" : { }
    }
  ........
```

**Comment by PierreBesson** [comment]
Thanks @ruddell in that case its doing just what we want. However rereading the article it seems Spring Boot 2 is going to break it 😢.
