### ISSUE TITLE
Upgrade to Angular 5

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-registry#236]
There are some error thrown during webpack compilation in current master. probably due to a deprecated option

```
[ERROR] Warning: Can't resolve all parameters for AlertService in /home/deepu/workspace/jhipster/jhipster-registry/node_modules/ng-jhipster/src/service/alert.service.d.ts: ([object Object], ?, [object Object]). This will become an error in Angular v5.x
[ERROR] Warning: Can't resolve all parameters for InterceptableHttp in /home/deepu/workspace/jhipster/jhipster-registry/node_modules/ng-jhipster/src/interceptor/interceptable-http.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
[ERROR] Template parse warnings:
[ERROR] The <template> element is deprecated. Use <ng-template> instead ("
[ERROR]   <div class="card">
[ERROR]     [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
[ERROR]       <div role="tab" id="{{panel.id}}-header"
[ERROR]         "): ng:///home/deepu/workspace/jhipster/jhipster-registry/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4

```

**Comment by pascalgrimaud** [comment]
It would be great to upgrade the front part, in the Registry.
IMO, it's important as the JHipster Registry is one of the best showcase of what we can do with JHipster.

@jdubois @deepu105 : if you agree and think it's worth doing it, I can take this part -> so I can integrate later some endpoints to do blue/green deployment easily ;-)

For the backend, I think we should wait for Spring Boot 2

**Comment by deepu105** [comment]
@pascalgrimaud I was thinking of doing it, but of course would be more than happy if you want to do it :) so go ahead please

**Comment by jdubois** [comment]
Yes please if you have the time... The Spring Boot 2 part is huge, I don't
have time for the Registry.

Le 23 janv. 2018 22:36, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
Just finished the migration to Angular5!
I need 1 or 2 days to test if everything works fine and I will submit a PR.

**Comment by jdubois** [comment]
Oh that's awesome!!!
We'll also need to update it for Spring Boot 2 as a few endpoints are moving (I already did it on generator-jhipster, so no big deal), and of course check it all works with Spring Boot 2 before the JHipster 5 release.

**Comment by pascalgrimaud** [comment]
Yes, the upgrade to SpringBoot2 should be done in another PR, as this one will change a lot of files.

No promise, but I can try to do the migration to Spring Boot 2 too

**Comment by jdubois** [comment]
Done by @pascalgrimaud
