### ISSUE TITLE
Registry is broken for monolith apps

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-registry#237]
Registry, in general, seems to broken when using with a JHipster monolith app (I haven't tried a microservice setup recently so not sure its fine there, but I would assume its broken there as well)
I tried both latest release using Docker and current master.

Issues I found apart from #236 
You are logged out when choosing a registered app in any dropdowns, and the content of screen doesn't change
Once logged out you cant go to any screen as you end up in the same login loop, look at the header in image
![image](https://user-images.githubusercontent.com/1107223/35272755-a15a7df2-0036-11e8-9031-0d004a30a243.png)
If you refresh the screen and try to log in again and you get below
![image](https://user-images.githubusercontent.com/1107223/35272811-d0ec8a7e-0036-11e8-82ae-3fde41f3b017.png)
If you try swagger for the registered app you get `Can't read swagger JSON from http://localhost:8761/services/jhtemp/jhtemp:95856a791cca7ca1596367fb8f6615b1/v2/api-docs`

@PierreBesson @jdubois can anyof you verify this

Initially, I thought these were something to do with my app, but then I generated a fresh app and tried but the same behavior. My app config below

##### **JHipster Version(s)**

```
jhtemp@0.0.0 /home/deepu/workspace/temp/jhtemp
└── generator-jhipster@4.13.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "jhtemp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.3

node: v8.9.3

npm: 5.3.0

bower: 1.8.0

gulp:
[12:15:15] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.17.1, build 6d101fb

Congratulations, JHipster execution is complete!

**Comment by deepu105** [comment]
I tried with registry 3.1.2 but same behavior may be the issue is with the app created using master branch of generator

**Comment by pascalgrimaud** [comment]
@deepu105 : I can have a look right now. In production, we use 3.1.2 without any problem

**Comment by pascalgrimaud** [comment]
@deepu105 : everything works fine for me

1) generate JHipster monolith with Eureka as service discovery, using master branch. Here my `.yo-rc.json` :
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "2ff8b2f4ae85e6e8e606749d5b52975f10141c8d",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

2) launch: `./mvnw clean package -Pprod` because it needs prod profile

3) start registry: `docker-compose -f src/main/docker/jhipster-registry.yml up -d`

4) start MySQL: `docker-compose -f src/main/docker/mysql.yml up -d`

5) launch app: `java -jar target/*.war`

![capture d ecran de 2018-01-23 13-16-39](https://user-images.githubusercontent.com/9156882/35275372-ccf4d544-003f-11e8-83bd-46d927e1e6a6.png)

![capture d ecran de 2018-01-23 13-16-51](https://user-images.githubusercontent.com/9156882/35275376-ced1c462-003f-11e8-8ac7-f0e71b25c1ca.png)

I can navigate without beeing log out. I'm using private navigation, so no problem for old cache

**Comment by pascalgrimaud** [comment]
Your app, with Gradle, works fine for me too.

![capture d ecran de 2018-01-23 13-31-37](https://user-images.githubusercontent.com/9156882/35275979-e086cf66-0041-11e8-8ab2-6527610c981d.png)
![capture d ecran de 2018-01-23 13-31-50](https://user-images.githubusercontent.com/9156882/35275981-e1dee01a-0041-11e8-8ab8-435873213501.png)
![capture d ecran de 2018-01-23 13-32-05](https://user-images.githubusercontent.com/9156882/35275982-e35ad0de-0041-11e8-858b-92035abef2fc.png)

**Comment by deepu105** [comment]
Strange, Sendil was able to reproduce the issue


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
How do you start your application?

**Comment by deepu105** [comment]
@pascalgrimaud did you access and sign into the generated application before accessing the admin pages from Registry?  Coz it seems it works if are logged into the app. I tried with a microservice as well and have the same issue

**Comment by pascalgrimaud** [comment]
No, I only opened the registry. I didn't open the application at all

**Comment by deepu105** [comment]
Ok, for me it still doesnt work even if i log in to the apps. This is very annoying damn.

**Comment by deepu105** [comment]
And I get the below in logs of the application
```
2018-01-23 13:46:15.166  INFO 6641 --- [ XNIO-2 task-27] c.m.myapp.security.jwt.TokenProvider     : Invalid JWT signature.
2018-01-23 13:46:15.169  WARN 6641 --- [ XNIO-2 task-27] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource
2018-01-23 13:46:15.180  INFO 6641 --- [ XNIO-2 task-28] c.m.myapp.security.jwt.TokenProvider     : Invalid JWT signature.
2018-01-23 13:46:15.182  WARN 6641 --- [ XNIO-2 task-28] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource

```

**Comment by pascalgrimaud** [comment]
@deepu105 :
- can you try in private navigation, so there won't be any old cache
- in the other ticket, I can saw `10.0.3.98:8443` -> did you try to configure https ?

**Comment by deepu105** [comment]
The other was using the app i currently work on which is already on https, but the one here is default generated app

**Comment by deepu105** [comment]
I'm gonna try from scratch again and use a private window

**Comment by pascalgrimaud** [comment]
Let me know if you need more testing, I will be able to do that.
So don't hesitate to ping me.

**Comment by pascalgrimaud** [comment]
Just in case:
- you need to start monolith in production profile, because in dev, you have:
```
eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: false # By default, the JHipster Registry is not used in the "dev" profile
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
```
- in production, you don't have swagger, so you need to specify it, when starting the app, using `--spring.profiles.active=prod,swagger`
- just be sure your monolith can get the config, provided by the Registry, so it will use the same jhipster.security.authentication.jwt.secret

**Comment by deepu105** [comment]
Yes I started them in prod profile.
I tested using the spring boot 2 branch of the generator and it works.

**Comment by deepu105** [comment]
So there is something strange when using master branch. I'm try gain but this time i'm gonna start the registry using the docker file generated in the app

**Comment by deepu105** [comment]
And yes, indeed that works. So the issue is if I run the regitry directly using `./mvnw` from master branch or if I use a docker file outside of the one generated. I'm gonna check what is the difference

**Comment by deepu105** [comment]
I dont see any difference between the docker compose files I used. Now i'm confused

**Comment by deepu105** [comment]
I'm giving up on it for now as I atleast found a setup that works and will use that for my demo.
@pascalgrimaud if my app is running https, do I have to do anything special in the registry?

**Comment by PierreBesson** [comment]
@deepu105 The different might be in the spring profiles loaded (by the registry). Also make sure your monolith app has this fix: https://github.com/jhipster/generator-jhipster/pull/6949

**Comment by pascalgrimaud** [comment]
@deepu105 : if you registry is not running in https, I don't think there are some special thing to do.
The communication between your application and the registry is based on the `eureka.client.service-url.defaultZone` and `spring.cloud.config.uri`, which uses http

**Comment by deepu105** [comment]
I figured out the issue, since the registry was not started from the docjer folder of teh apps, the path for the `./central-server-config` was resolving wrong and hence the same JWT token was not being used. I guess we need to make the docs more clear about this one

**Comment by deepu105** [comment]
So for clarify the issue was when I did the below.
1. Start the registry using a standalone docker-compose file with below
```
jhipster-registry:
    image: jhipster/jhipster-registry:v3.2.4
    volumes:
        - ./central-server-config:/central-config
    environment:
        - SPRING_PROFILES_ACTIVE=dev,native,swagger
        - SECURITY_USER_PASSWORD=admin
        - JHIPSTER_REGISTRY_PASSWORD=admin
        - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
    ports:
        - 8761:8761
```
2. Go to another folder and generate a default app with registry enabled.
3. Start the app. App connects to the registry successfully but then there is the above-mentioned behavior and seems like the app and registry is not using same JWT token. Something to do with the relative path of the `central-config/` I guess. @PierreBesson correct me if i'm wrong as you know this way better than me

**Comment by PierreBesson** [comment]
Yes the `central-config` folder should go along with `jhipster-registry.yml`, I will check it later... 
Then I'm having some doubts here, maybe:
`        - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/`
should be:
`        - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/central-config/localhost-config/`
But it should not change anything.

**Comment by jdubois** [comment]
OK, looks like you found the issue! Can I be of any help?

**Comment by pascalgrimaud** [comment]
just tested it, and it works fine with last Registry v4.0.0
So we can close this
