### ISSUE TITLE
Migration to Spring Boot 2

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#242]
I open this ticket for the migration to Spring Boot 2

I don't know if someone already started this.
I can start the work and will probably push a branch.

**Comment by jdubois** [comment]
It's yours if you vonlonteer :-)
Copy what I did in the generator, it should be alright.

**Comment by pascalgrimaud** [comment]
Yes, already started the work this morning

**Comment by pascalgrimaud** [comment]
It's working on my machine.
I need some free time for testing if it's working for all configuration.

I will need a review from you, @jdubois, specially for the Security part, as I'm not expert in this domain.
I put these 2 links which helped me:
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#security
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0#changing-the-username-and-password

**Comment by jdubois** [comment]
Yes I know @pascalgrimaud - I'll have a look next week.
Testing microservices options is one of the big remaining tasks for JHipster 5.

**Comment by pascalgrimaud** [comment]
TODO:
- The configuration page doesn't work -> I'm working on this, and trying to make it compatible with SB1 too
- Swagger doesn't work for OAuth2
- I didn't test with UAA yet

**Comment by pascalgrimaud** [comment]
**Metrics**

it works nice for Spring Boot 1 and Spring Boot 2, I did nothing, strange!

**Configuration**

- For `/management/env`
There is an issue in current master, I will open a ticket for that. We don't see the properties from `/management/env`

- For `/management/configprops`
The JSON has changed. Here an extract:

```yaml
{
  "contexts": {
    "jhipster-registry-1": {
      "beans": {
        "management.trace.http-org.springframework.boot.actuate.autoconfigure.trace.http.HttpTraceProperties": {
          "prefix": "management.trace.http",
          "properties": {
            "include": [
              "COOKIE_HEADERS",
              "RESPONSE_HEADERS",
              "REQUEST_HEADERS",
              "TIME_TAKEN"
            ]
          }
        }
``` 

Looking at this [code](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.service.ts.ejs#L34), I should use:
`const propertiesObject = res.body.contexts['jhipster-registry'].beans;` but it doesn't work because in the JSON, we can see `jhipster-registry-1` instead of `jhipster-registry`.

That means the ApplicationContext Id is different for monolith and microservice.
I confirmed that, using this endpoint:

```java
@Autowired
private ApplicationContext app;

@GetMapping("/get-application-context-id")
public String getApplicationContextId() {
    return app.getId();
}
```

Here the ticket from Spring Boot: https://github.com/spring-projects/spring-boot/issues/11023

In all cases, I have both endpoints working and correctly displayed in our Registry, and for both: SB1 and SB2, so our Registry is compatible with SB1.

**Comment by jdubois** [comment]
Oh the `jhipster-registry-1` issue is very annoying - I thought I solved this in the main generator.... Maybe we should better iterate over all children `contexts`?

**Comment by pascalgrimaud** [comment]
In the main generator, there is no issue (excepting for `/management/env` but it's for another reason) because the Application Context Id is the same than the application, without this `-1`.

There are only issues in applications with Spring Cloud, so with our microservices

**Comment by pascalgrimaud** [comment]
But I resolved these issues in the spring boot 2 branch, it's working now :)

**Comment by jdubois** [comment]
OK thanks! Can you do it in the generator too?

**Comment by pascalgrimaud** [comment]
Yes, I wanted to do it this morning, but didn't have time

**Comment by pascalgrimaud** [comment]
Closed as the PR has been merged
