### ISSUE TITLE
/eureka/** is not open to CORS on dev environment

### ISSUE THREAD

**Issue by henri-tremblay** [jhipster/jhipster-registry#246]
##### **Overview of the issue**

The `CorsFilter` is used to allow CORS on pretty much everything. However, the `/eureka/**` URL isn't covered by it. The Zuul proxy is somewhere else in standalone.

##### **Motivation for or Use Case**

I tried to access `/eureka/apps/XXX` from a website to get the deployment URL of an app. It is a toy app. It doesn't work.

##### **Reproduce the error**

Try to access http://localhost:8761/euraka/apps/XXX from any HTML app in a browser.

##### **Suggest a Fix**

Configure Zuul correctly in dev to allow it I guess.

##### **JHipster Registry Version(s)**

Current master (bbbc407)

##### **Browsers and Operating System**

Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I'm guessing you have the port right in your code? 8461 -> 8761

**Comment by henri-tremblay** [comment]
Yes sorry.

**Comment by jdubois** [comment]
Oh yes, because that's not supposed to be used from the front-end, it's only for communicating between Eureka clients/servers.
What is the interest in accessing this from a browser?

**Comment by henri-tremblay** [comment]
It's for a little demo I'm doing. It allows listing the instances of a given app on a local GUI. The workaround is to use `api/eureka/applications` and the filter per application name. It works.

**Comment by PierreBesson** [comment]
@henri-tremblay I guess this could be enabled for dev, if you reallly want this please do the PR.

**Comment by henri-tremblay** [comment]
:-) @PierreBesson I would have already done it if I knew how to fix it :-)

**Comment by PierreBesson** [comment]
@henri-tremblay, The relevant code is here : https://github.com/jhipster/jhipster-registry/blob/da29f59f868c2ad36b10a8b3585e5d4ebad8339b/src/main/java/io/github/jhipster/registry/config/WebConfigurer.java#L157

**Comment by henri-tremblay** [comment]
No. Eureka seems to be somewhere else. It doesn't use the configurer. Unless I missed something (which is always possible).

**Comment by PierreBesson** [comment]
@henri-tremblay Thinking about it more, I think you are right, as the Eureka API comes from the Eureka server (https://github.com/Netflix/eureka) itself which is not a exposed through the spring servlet. So I think passing through Zuul might be a better choice.
