### ISSUE TITLE
configserver.status is wrong

### ISSUE THREAD

**Issue by gmarziou** [jhipster/jhipster-registry#25]
I have a service srv1 in dev profile, when it starts and connects to the registry it prints:

	Config Server: 	http://localhost:8761/config/master/srv1-dev.yml

This URL returns a 404 error, the correct URL should be:

	Config Server: 	http://localhost:8761/config/srv1/dev/master

This is configured in application.yml:

~~~json
# Property used on app startup to check the config server status
configserver:
    name: JHipster Sample Spring Cloud Config
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml
~~~

**Comment by PierreBesson** [comment]
I found the bug :smile: !

The .yml format works, it is just that it needs a trailing `/` for some reason.
Try this: `http://localhost:8761/config/master/srv1-dev.yml/`

**Comment by gmarziou** [comment]
This looks more like a hack to me.
As the doc says there are 5 URL formats, personally I prefer the first one.
Why do you prefer the 3rd one?

> The HTTP service has resources in the form:
> 
> /{application}/{profile}[/{label}]
> /{application}-{profile}.yml
> /{label}/{application}-{profile}.yml
> /{application}-{profile}.properties
> /{label}/{application}-{profile}.properties

**Comment by PierreBesson** [comment]
I prefer the 3rd one because it is the most readable one. In my opinion, this is just to quickly check that the right properties are loaded. I agree the first one should be the one that is used when using the registry's API. But for quick check, nothing beats yaml I think.

**Comment by gmarziou** [comment]
But 1st format returns also yaml, it mainly depends on the http accept headers that browser sends, depending on browser you can get xml or yaml.

**Comment by gmarziou** [comment]
Anyway do as you want, it's not important and I can easily use the restful one for my setup.
