### ISSUE TITLE
Strings literals should be placed on the left side when checking for equality

### ISSUE THREAD

**Issue by Zalimben** [jhipster/jhipster-registry#250]
##### **Overview of the issue**
It is preferable to place string literals on the left-hand side of an equals() or equalsIgnoreCase() method call.

##### **Motivation for or Use Case**
This prevents null pointer exceptions from being raised, as a string literal can never be null by definition.

##### **Suggest a Fix**
Place string literals on the left-hand side
JHipsterRegistryApp.java#L:99

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@Zalimben : would you like to contribute to fix this ?

**Comment by jdubois** [comment]
I'm not such a big fan of this, I find the code less readable.
And if code/test correctly that type of bug never happens.

Le 9 mars 2018 7:56 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by PierreBesson** [comment]
PR merged
