### ISSUE TITLE
Consumes a lot of RAM

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [jhipster/jhipster-registry#269]
Just start it, it consumes 14GB of virtual, and ~4GB of real RAM. Running in docker compose ,
next options does not help much:
     environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - _JAVA_OPTIONS=-Xmx512m -Xms256m

**Comment by vitaliy-kuzmich** [comment]
ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JAVA_OPTS="" \
    SPRING_PROFILES_ACTIVE=prod,native \
    GIT_URI=https://github.com/jhipster/jhipster-registry/ \
    GIT_SEARCH_PATHS=central-config

But above command overrides JAVA_OPTS... it does not take any affect, check by your self...

**Comment by vitaliy-kuzmich** [comment]
printenv JAVA_OPTS

**Comment by jdubois** [comment]
This totally depends on your OS, your JVM, etc...
This doesn't look at all like a JHipster Registry bug, it's just your JVM that is not well configured - could you post this on StackOverflow with the jhipster tag?

**Comment by jdubois** [comment]
Oh no problem, thanks for commenting!
