### ISSUE TITLE
Compatibility with SCSS is not good

### ISSUE THREAD

**Issue by bairui100** [jhipster/jhipster-registry#271]
yarn version: 1.6.0
npm version: 5.6.0
node.js version: 8.11.2

when i use "npm install" and "npm start" . it show :
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported

I think it's version compatibility in package.json

**Comment by pascalgrimaud** [comment]
It's related to Node Sass with your environment (windows, linux or mac) , not to JHipster.
Not sure we can do something here.

Do you have an issue when launching the app ? Or it's just this warning message

**Comment by bairui100** [comment]
![image](https://user-images.githubusercontent.com/33535023/40887159-b2b4b642-6776-11e8-9913-f7a8e91b87b4.png)

When I use "npm start", something goes wrong.

But when I started another gateway project, everything was fine.Gateway to use CSS

**Comment by bairui100** [comment]
I upgraded my NPM to the latest version 6.1.0
Finding that node-sass 4.5.0 in package.json does not support the latest version of NPM, I changed the version of node-sass to 4.9.0.
But there are new problems：
![image](https://user-images.githubusercontent.com/33535023/40887337-e7caa01e-6779-11e8-84c6-14d7ace53bcf.png)
![image](https://user-images.githubusercontent.com/33535023/40887343-faf56c50-6779-11e8-98d3-9adbf8b8dfd3.png)

**Comment by pascalgrimaud** [comment]
I don't think it's related to NPM version but directly to Node version.
I suggest you to have a look at:
- https://github.com/sass/node-sass/issues
- https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md

There are a lot of issues with the same error you have.
Sometimes, this command can resolve your issue: `npm rebuild node-sass`

I'm closing this, as it's not a problem with jhipster-registry, but with the node sass library.
