### ISSUE TITLE
I have to do a little change to startup the `jhipster-registry`. 

### ISSUE THREAD

**Issue by xiaoshao** [jhipster/jhipster-registry#275]
I am following the readme to start registry. But I can't access the it by `localhost:8671` after start it.

I just start it by
```
mvn clean package -DskipTests
java -jar registry.war
```
because it is failed when running `mvnw`

**Comment by pascalgrimaud** [comment]
it's `localhost:8761`

We can't help you with the only information:
> it is failed when running mvnw

We need to have your log output.

I'm closing this, because we don't have enough information to help you and I'm sure the last version works well, as we did the demo at JHipster Conf yesterday.

**Comment by xiaoshao** [comment]
The error for `./mvnw -Pdev,webpack` as following.
```
[ERROR] error Command "webpack:build:dev" not found.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.800 s
[INFO] Finished at: 2018-06-22T15:56:42+08:00
[INFO] Final Memory: 39M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (webpack build dev) on project jhipster-registry: Failed to run task: 'yarn run webpack:build:dev' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

And I have fix the `./mvnw` failed by downgrade the node version to 8 from 10. 
Could you add the node version as the pre-requirement.

But I still can't access the dashboard, I have to run yarn start and access by `localhost:9000`

**Comment by xiaoshao** [comment]
and my yarn version is 
```
➜  SpringCloudConfigClient yarn -version
1.7.0
```

**Comment by pascalgrimaud** [comment]
I reopen the ticket as we have an issue in our `pom.xml`. Here all instructions:

1st solution:
- clone the project
- install the lib: `yarn install`
- build the front: `yarn webpack:build`
- launch maven: `./mvnw`

2nd solution:
- clone the project
- install the lib: `yarn install`
- modify in your `pom.xml`: `<arguments>run webpack:build:dev</arguments>` -> `<arguments>run webpack:build</arguments>` (you need to delete `:dev`)
- launch directly: `./mvnw -Pdev,webpack`

I will fix the `pom.xml` later or you can do it if you want :)
Thanks for the report

**Comment by jdubois** [comment]
If that's broken that probably means it also fails when you use the Heroku button so I'm cc'ing @jkutner 

We need to fix this quickly, I'll have time this afternoon if needed.

**Comment by jdubois** [comment]
Oh and @xiaoshao  could you put a better title to this issue

**Comment by pascalgrimaud** [comment]
@jdubois : it works well when deploying to Heroku because it uses `-Pprod,heroku -DskipTests` (there is no webpack profile here, which is used only for dev)
See https://github.com/jhipster/jhipster-registry/blob/master/app.json#L16

This issue is only for development

**Comment by jdubois** [comment]
Indeed thanks @pascalgrimaud it works on Heroku without any issue (cc @jkutner )

**Comment by jkutner** [comment]
Great! Thank you for being mindful of the Heroku button

**Comment by pascalgrimaud** [comment]
Closing this, as https://github.com/jhipster/jhipster-registry/issues/275 is merged
