### ISSUE TITLE
Jhipster registry v3.3.0 is not picking up environment variables

### ISSUE THREAD

**Issue by ganeshkrishnan1** [jhipster/jhipster-registry#280]
##### **Overview of the issue**

v3.3.0 of jhipster ignores the environment variable.

##### **Motivation for or Use Case**

Unable to set custom password. Jhipster in product reverts to default admin/admin
This is a critical issue as the production is going back to default password

##### **Reproduce the error**

Either in docker or as command line pass new password
Docker:
            - SPRING_PROFILES_ACTIVE=dev
            - SECURITY_USER_PASSWORD=wotmeworry
Command Line:
./jhipster-registry-3.3.0.war --security.user.password=wormeworry

Login to console. The set password won't work. You have to login as admin/admin

##### **Related issues**

None.

##### **Suggest a Fix**

I had to go back to v3.2.4 and it works correctly.

##### **JHipster Registry Version(s)**

v3.3.0

##### **Browsers and Operating System**

Linux Ubuntu 18.04

- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Looking at the config: https://github.com/jhipster/jhipster-registry/blob/master/src/main/resources/config/application-dev.yml#L37

Can you try: SPRING_SECURITY_USER_PASSWORD instead ?

**Comment by ganeshkrishnan1** [comment]
Perfect. Works. 
Which means we need to update the documentation. I will send a pull request for the docs

**Comment by jdubois** [comment]
Oh yes please

**Comment by ganeshkrishnan1** [comment]
Created pull request. Closing this issue
