### ISSUE TITLE
yarn global upgrade generator-jhipster gives error lockfile is outdated

### ISSUE THREAD

**Issue by tibistibi** [jhipster/jhipster-registry#286]
##### **Overview of the issue**

I want to upgrade my jhipster application to the latests version. when running the command:

     yarn global upgrade generator-jhipster

it gives me the error:

    error Outdated lockfile. Please run `yarn install` and try again.

when i run yarn install it runs fine but when i rerun ` yarn global upgrade generator-jhipster` i still get the same error.

##### **Motivation for or Use Case**

I can not upgrade jhipster which i would like to do.

##### **Reproduce the error**

run:

     yarn global upgrade generator-jhipster
     yarn install
     yarn global upgrade generator-jhipster

full result:

    yarn global upgrade generator-jhipster
    yarn global v1.9.2
    error Outdated lockfile. Please run `yarn install` and try again.
    info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

##### **JHipster Registry Version(s)**

i'm at the moment on version 4.14.4

##### **Browsers and Operating System**

I use ubuntu 16.04.5

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
This is the repo for the JHipster Registry, I think you are looking for https://github.com/jhipster/generator-jhipster

**Comment by tibistibi** [comment]
ah sorry about that.

luckily i found the solution already (and thanks to your response i could find this issue).

the error message is unclear but what solved it was using 
sudo 
probably the lockfile was not outdated but could not be read becasue of rights.

i will close this issue
