### ISSUE TITLE
docker-compose requires empty secret before it will use base64-secret

### ISSUE THREAD

**Issue by jsm174** [jhipster/jhipster-registry#291]
##### **Overview of the issue**

I built a jhipster docker setup using: `jhipster docker-compose`

Running the standard `docker-compose up`, I was noticing:

```
jhipster-registry_1  | 2018-09-11 17:31:52.526  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: dev,composite,swagger
jhipster-registry_1  | 2018-09-11 17:31:56.095  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1  | 2018-09-11 17:31:57.844  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: dev
jhipster-registry_1  | 2018-09-11 17:31:57.854  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
jhipster-registry_1  | 2018-09-11 17:31:58.030 ERROR 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : WARNING! You are using the default JWT secret token, this **must** be changed in production!
jhipster-registry_1  | 2018-09-11 17:31:58.030  WARN 1 --- [           main] i.g.j.r.security.jwt.TokenProvider       : Warning: the JWT key used is not Base64-encoded. We recommend using the `jhipster.security.authentication.jwt.base64-secret` key for optimum security.
```

Inspecting `central-server-config/application.yml` the `base64-secret` is there:

```
jhipster:
    security:
        authentication:
            jwt:
                base64-secret: NzkwZWI0MWM3NjM4NmQ2OTE5NmE3ZDQ0OTdiNmI5YTM4MzkxN2NmZDhjZGNjYjM2NzJjYjNiYTQzZGVmOTQ4MjdjNDFkMDU0MzZjYjk0NmVmYTBiZWE1NTQ0YzhjNWEzNjM1YQ== 
jhipster.security.authentication.jwt.base64-secret
```

Going to the admin console at `http://localhost:8761/#/` I get:

`
jhipster-registry_1  | 2018-09-11 17:35:33.437 ERROR 1 --- [  XNIO-2 task-7] i.g.j.r.aop.logging.LoggingAspect        : Exception in io.github.jhipster.registry.web.rest.UserJWTController.authorize() with cause = 'NULL' and exception = 'The signing key's size is 376 bits which is not secure enough for the HS512 algorithm.  The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS512 MUST have a size >= 512 bits (the key size must be greater than or equal to the hash output size).  Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS512)' method to create a key guaranteed to be secure enough for HS512.  See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.'
`

If you look at any of the `jhipster-registry/src/main/resources/config/application-*.yml` files, the secrets are set to:

`this-secret-should-not-be-used-read-the-comment`

47 characters / 376 bits.

If you look at [TokenProvider.java](https://github.com/jhipster/jhipster-registry/blob/master/src/main/java/io/github/jhipster/registry/security/jwt/TokenProvider.java#L57), it looks for an empty secret before switching to the base64 version.

I've updated my `central-server-config/application.yml` with an empty secret:

```
jhipster:
    security:
        authentication:
            jwt:
                secret:
                base64-secret: NzkwZWI0MWM3NjM4NmQ2OTE5NmE3ZDQ0OTdiNmI5YTM4MzkxN2NmZDhjZGNjYjM2NzJjYjNiYTQzZGVmOTQ4MjdjNDFkMDU0MzZjYjk0NmVmYTBiZWE1NTQ0YzhjNWEzNjM1YQ== 
```

And everything launches fine:

```
jhipster-registry_1  | 2018-09-11 17:47:30.859  INFO 1 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: dev,composite,swagger
jhipster-registry_1  | 2018-09-11 17:47:34.134  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
jhipster-registry_1  | 2018-09-11 17:47:35.865  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: dev
jhipster-registry_1  | 2018-09-11 17:47:35.874  INFO 1 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
jhipster-registry_1  | 2018-09-11 17:47:38.135  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
```
secret must be getting picked up from one of those files. 

##### **Reproduce the error**

1) `jhipster`(create new generic microservice project)
2) `./gradlew bootWar -Pprod buildDocker`
3) `jhipster docker-compose`
4) `docker-compose up`

##### **Related issues**

Similar to close issue:  https://github.com/jhipster/jhipster-registry/issues/289

##### **Suggest a Fix**

Not sure, but I believe secret shouldn't be defaulted in application-*.yml files.

##### **JHipster Version(s)**

```
jason@0.0.0 /Users/jmillard/jh-hipster
└── generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "jason",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v10.10.0

npm: 6.4.1

yarn: 1.7.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

macOS High Sierra 10.13.6

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Closing this in favour of #8301
