### ISSUE TITLE
401 invalid token error when try to explore swagger API of microservices from  jhipster registry

### ISSUE THREAD

**Issue by mkawczynski07** [jhipster/jhipster-registry#294]
##### **Overview of the issue**

I run jhipster registry from sources with:
`
$ ./mvnw -Pprod
`
I added UAA and one microservice from jhipster with defaults. After all of them build I am unable to check API definitions from jhipster registry. I get **401 invalid token** error.

##### **JHipster Registry Version(s)**
JHipster Registry 4.0.1

##### **Browsers and Operating System**
Chrome Version 69.0.3497.81 (Official Build) (64-bit)
Kubuntu 18.04 LTS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
UAA support for the registry was just recently added and will be in the next release.  If you want to have it early, you can make the following changes:

 - In your UAA app's UaaConfiguration.java, add `.authorities("ROLE_ADMIN")` [here](https://github.com/jhipster/generator-jhipster/commit/8b933093a6aff87c90bef22e1c5894134c0ad231).

 - Then you can use the `develop` tag for the `jhipster-registry` Docker image, and add the `uaa` profile to that container's `SPRING_ACTIVE_PROFILES`
   - If you prefer to run the JHipster Registry from source, you can clone the [`jhipster-registry` repository](https://github.com/jhipster/jhipster-registry) and check out the `develop` branch
   - Make sure the registry uses the `uaa` profile
