### ISSUE TITLE
Unable to run JHipster registry in AWS

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/jhipster-registry#298]
##### **Overview of the issue**

I can login when I deploy it in AWS using [Elastic Beanstalk](https://docs.aws.amazon.com/quickstarts/latest/webapp/welcome.html?icmpid=docs_eb_console_new)

In particular I receive the following error:
```
ERROR Error: Uncaught (in promise): e: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":404,"statusText":"OK","url":"http://ec2-18-202-170-229.eu-west-1.compute.amazonaws.com/api/profile-info","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://ec2-18-202-170-229.eu-west-1.compute.amazonaws.com/api/profile-info: 404 OK","error":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;api&#47;profile-info</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.32</h3></body></html>"}
```

##### **Motivation for or Use Case**

I am simply trying to deploy my microservice architecture for the first time to AWS as test for before the real production environment deployment

##### **Reproduce the error**

1. Clone this repository locally
2. Following the instruction at [Deploying to AWS](https://www.jhipster.tech/aws/) compile with `./mvnw -Pprod package` 
3. Rename compiled file `jhipster-registry-4.0.3.war.original` which is in the sub-folder `target` to `jhipster-registry-4.0.3.war`
4. Upload the renamed file `jhipster-registry-4.0.3.war` using [Elastic Beanstalk Management Console](https://console.aws.amazon.com/elasticbeanstalk/home) and choosing the option `Platform to Tomcat`

You can see the error in the console of the browser accessing 
[My Test](http://ec2-18-202-170-229.eu-west-1.compute.amazonaws.com)

##### **Related issues**

I didn't find any

##### **Suggest a Fix**

I guess the best fix would be to document the deployment procedure step by step, eventually with the necessary environmental variable to be set. A kind of procedure for dummy so I just can follow those instructions and make it work as it is before I make any customization

##### **JHipster Registry Version(s)**

v4.0.3

##### **Browsers and Operating System**

This issue is independent from the browser and operating system

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Deploying the registry in Tomcat 8 is not exactly option we recommended, so I'm not sure we should spend some time documenting it. Any reason why you don't deploy as an executable war?

**Comment by alexsintoni** [comment]
Hi @gmarziou and thanks for the reply.
There is any particular reason that I use Tomcat but it was the only option which worked with [Elastic Beanstalk](https://docs.aws.amazon.com/quickstarts/latest/webapp/welcome.html?icmpid=docs_eb_console_new)

I tried to choose Java as Platform, but that option does not even start the app properly and I am not sure why. Instead when I chose Tomcat, the app is green in AWS and it starts but I cannot login.
If you have a better way, would you mind to tell me it? or direct me to a step by step procedure?

I have already tried the `aws sub-generator` described at [Deploying to AWS](https://www.jhipster.tech/aws/) but I get `Error: ERROR! Sorry deployment for this database is not possible`.
Then I tried directly using the AWS console [Elastic Beanstalk Management Console](https://console.aws.amazon.com/elasticbeanstalk/home) and Tomcat was the only option working

**Comment by gmarziou** [comment]
I rewrote title as it seems more descriptive to me because you tried 2 different ways and both failed.
Hopefully, AWS experts may have a look at thtis issue with this tile and help you as I don't use AWS myself.

**Comment by alexsintoni** [comment]
@gmarziou perfect, really thanks a million for your support. Have a nice day man :)

**Comment by ruddell** [comment]
I wasn't able to get the registry started in a local Tomcat docker container, so this looks unrelated to AWS.  The backend doesn't start up for some reason.

**Comment by PierreBesson** [comment]
I don't see why we should support Tomcat. We already provide a jar deployments and a docker image which uses an embedded undertow.

I'm closing this issue as we are not going to support this method of running the registry.
I don't know much about Elastic Bean Stalk but it should be able to run docker containers just fine.
