### ISSUE TITLE
Problem to configure docker health check

### ISSUE THREAD

**Issue by dami1c** [jhipster/jhipster-registry#301]
##### **Overview of the issue**
I don't succeed to activate the docker health check when i run the jhipster-registry docker image.

##### **Motivation for or Use Case**
Need health check to monitor jhipster-registry server status.

##### **Reproduce the error**
I tried to enable the docker healtcheck calling the /management/health api with curl
`$ docker run --health-cmd='curl http://127.0.0.1:8761/management/health || exit 1' jhipster/jhipster-registry:latest`

but the health status stay unhealthy :
```
$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                     PORTS               NAMES
78ffe00e0a3a        jhipster/jhipster-registry:latest   "/bin/sh -c 'java   …"   8 minutes ago       Up 8 minutes (unhealthy)   8761/tcp            friendly_hodgkin
```

When I install manually curl in the container with
```
$ winpty docker exec -it 78ffe00e0a3a //bin//sh
/ # apk add --no-cache curl
```
the health status become healthy
```
$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                      PORTS               NAMES
78ffe00e0a3a        jhipster/jhipster-registry:latest   "/bin/sh -c 'java   …"   34 minutes ago      Up 34 minutes (healthy)     8761/tcp            friendly_hodgkin
```

##### **Related issues**
no one

##### **Suggest a Fix**
curl isn't installed in the jhipster-registry docker image. I think you should complete the RUN step with "apk add --no-cache curl" in the dockerfile.
What do you think?

##### **JHipster Registry Version(s)**
V4.0.3

##### **Browsers and Operating System**
This issue is independent from the browser and operating system
- [ X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Adding `curl̀` won't increase so much the Docker image size.
So yes, do you want to contribute plz ?

**Comment by pascalgrimaud** [comment]
Closing this, as the PR has been merged
