### ISSUE TITLE
No frontend with WAR-distribution

### ISSUE THREAD

**Issue by fjakop** [jhipster/jhipster-registry#309]
##### **Overview of the issue**

After downloading the WAR and starting it I get an error page at localhost:8761, no frontend is displayed.

##### **Motivation for or Use Case**

I can not use the registry's frontend.

##### **Reproduce the error**

1. Download and save jhipster-registry-4.0.5.war
2. Create folder _central-config_ besides the war
3. Create _application.yml_ in _central-config_ and copy contents from https://github.com/jhipster/jhipster-registry-sample-config/blob/master/application.yml into it
4. Start registry with `java -jar jhipster-registry-4.0.5.war --spring.security.user.password=admin --jhipster.security.authentication.jwt.secret=secret-key --spring.cloud.config.server.composite[0].type=native --spring.cloud.config.server.composite[0].search-locations=file:./central-config`
6. Wait for startup (no errors on console) and navigate your browser to http://localhost:8761/

--> It shows "Your request cannot be processed :("

If I download the sources and build the WAR myself it works.

##### **Related issues**

Not found

##### **JHipster Registry Version(s)**

4.0.5

##### **Browsers and Operating System**

Windows 7, Chrome 70.x, Java 8

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
thanks for opening this, I forgot it.
I confirm the issue

**Comment by jdubois** [comment]
Thanks also! I was just going to test this! It shouldn't take much time

**Comment by jdubois** [comment]
OK normalement c'est bon maintenant!
A ce propos je vais sans doute faire une 4.0.6 aujourd'hui :-)
