### ISSUE TITLE
Logs / Health et al. not working on Registry for other services

### ISSUE THREAD

**Issue by fjakop** [jhipster/jhipster-registry#311]
##### **Overview of the issue**

When I start JHipster Registry 4.0.6 (WAR) and try to view logs, health etc. for other registered services
  * it does not show these data
  * the frontend is broken, i.e. when I click 'Home' I'm logged out and forced to sign in again

##### **Motivation for or Use Case**

The overviews for other services seem quite unusable for me.

##### **Reproduce the error**

1. Start Registry 4.0.6 WAR 
2. Start another Service, e.g. UAA which registers on Registry
3. Login to Registry and verify that UAA is registered
4. Go to Administration -> Logs
5. In Dropdown, choose "uaa"
  --> logfile does not change
6. Click "Home" button
  --> a logon screen appears
7. Sign in again
  --> You are still on logs page

There is no relevant console log in both Registry and UAA.

##### **Related issues**

Not found.

##### **JHipster Registry Version(s)**

4.0.6, but did not work in 4.0.5 and 4.0.4 either.

##### **Browsers and Operating System**

Windows 7, Chrome 70.x

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@fjakop : can you try the develop branch ? or jhipster/jhipster-registry:develop image
It is supposed to work since this PR https://github.com/jhipster/jhipster-registry/pull/278
Maybe you need to use the `uaa` profile for that.

I know the UAA support is really bad today, as it seems no one want to contribute / fix bug / improve this.

**Comment by xetys** [comment]
I'm still stuck with private stuff... Just can't get my self running
again..... However, I'll take a look



Julien Dubois <notifications@github.com> schrieb am Do., 8. Nov. 2018,
09:25:

**Comment by jdubois** [comment]
Thanks a lot @xetys - I see tons of people using UAA, so your work is definitely very important, then it's really sad none of them participate. Not sure how we can fix that :-(

**Comment by fjakop** [comment]
I've tried again with develop branch as suggested, but it does also not work. When I watch the browser console I see after switching logfile from registry to uaa (or any other registered service)

    zone.js?d135:2935 GET http://localhost:9000/services/uaa/uaa:17cab97f2bdb4335af68264c41284d44/management/logfile 401 (Unauthorized)
    zone.js?d135:2935 GET http://localhost:9000/management/logfile 401 (Unauthorized)
    zone.js?d135:2935 GET http://localhost:9000/services/payment/payment:a70ab39d79fdd3fbac2781f035d9bbcf/management/logfile 401 (Unauthorized)

In this example I first switched to uaa logs, then registry logs, then logs of payment service.

**Comment by ruddell** [comment]
@fjakop Are you sure you are using the `uaa` profile?  I cloned the repository, added `uaa` to `spring.profiles.active` in `bootstrap.yml`, and was able to manage a UAA app through the Registry admin pages.  Note that just running `./mvnw -Puaa` doesn't work

I get a 404 on the logs page but that's expected and the instructions to enable it are on the page.

**Comment by fjakop** [comment]
I've tested with `-Dspring.profiles.active=dev,uaa`, it works. As you mentioned, `./mvnw -Puaa` does not work.
