### ISSUE TITLE
Configurations returned as xml

### ISSUE THREAD

**Issue by mhewedy** [jhipster/jhipster-registry#321]
##### **Overview of the issue**

When my app that contains the client config has jackson xml as a dependency then the accept header looks like: `application/xml, text/xml, application/json, application/*+xml, application/*+json`..
Config server inside the jhipste registry should ignores the application/xml, text/xml and uses application/json and return json, but it returns XML (which it should not do) 

##### **Motivation for or Use Case**

Because the module/app depends on jackson xml  but it fails when try to read config from config-server.

##### **Reproduce the error**

create microservice A with a dependency on jackson-dataformat-xml and in the config server add a configuration like `A.yml`:

    some.property:
         - key1: value1
         - key2: value2 
When start the microservice A, it will try to communicate with the config server (jhipster resigestery) and return the properties in A.yml but the config server will return it in (unsupported) XML format.

##### **Related issues**

https://github.com/spring-cloud/spring-cloud-config/issues/306

##### **Suggest a Fix**

enformce config-server to ignore xml accept mime type

##### **Browsers and Operating System**

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by FalconIA** [comment]
same issue.

**Comment by mhewedy** [comment]
Any updates on this, this is causing a series issue for our jhipster apps

**Comment by jdubois** [comment]
I'm sorry but as nobody says on the ticket he's working on this, I guess nobody does!

To be honest this isn't really clear to me, why are you adding ` jackson-dataformat-xml ` as a dependency? @mhewedy you seem to understand the issue quite well, would you be ready to contribute to the project?

**Comment by PierreBesson** [comment]
This is an interesting bug. It seems it was fixed upstream https://github.com/spring-cloud/spring-cloud-config/pull/1171
So newer version of spring cloud config client should not have the issue.
