### ISSUE TITLE
jhipster-registry docker cannot authenticate to keycloak 

### ISSUE THREAD

**Issue by M-Fararjeh** [jhipster/jhipster-registry#329]
I started jHipster registry using docker, I update keycloak URL in YML file.
SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://127.0.0.1:9080/auth/realms/jhipster/protocol/openid-connect/token
when jHipster started the authentication not working.
![image](https://user-images.githubusercontent.com/6216279/52143188-de090500-266b-11e9-8db4-4752ba59eb9c.png)

![image](https://user-images.githubusercontent.com/6216279/52143226-f2e59880-266b-11e9-8f20-ba2cae47e226.png)

![image](https://user-images.githubusercontent.com/6216279/52143253-07c22c00-266c-11e9-9f46-274015e6e13a.png)

what is the problem ??

**Comment by pascalgrimaud** [comment]
When you start the registry inside Docker, it will be in another network.
That means the Registry and Keycloak can't communicate.

To solve your issue, it depends on a lot of thing:
- what is your OS
- how do you start your Keycloak

**Comment by M-Fararjeh** [comment]
No, same network. 

I created monolithic application connected to keycloak, It works fine.

**Comment by pascalgrimaud** [comment]
No, if you start your registry inside Docker and your keycloak in your host, the Docker container will be in another network, unless you modify it to specify the use of network host.

That's how Docker works. 

As you didn't provide enought information, it is impossible to reproduce / help.

**Comment by M-Fararjeh** [comment]
![image](https://user-images.githubusercontent.com/6216279/52164050-47d0ef80-26fc-11e9-86ca-bcc8e1e4f58b.png)

keycloak and registry started from container and in the same network.

**Comment by relio** [comment]
@M-Fararjeh, if you have followed the instructions provided by [keycloak](https://hub.docker.com/r/jboss/keycloak/) to set up your docker box, you should have created this network:

`docker network create keycloak-network`

If you inspect the keycloak container you should see its reference in the network part of the output:

`"Networks": {
                "keycloak-network": {`

If you have a standard docker jhipster registry, it should have a standard network:

`"Networks": {
                "docker_default": {`

So, as it was pointed out in the previous posts, the keycloak container cannot communicate with the jhipster registry as they are part of different networks. You can quickly fix this just making jhipster registry container (_docker_jhipster-registry_1_ in my case) part of the keycloak network with:

`docker network connect keycloak-network docker_jhipster-registry_1`

Now, if you inspect _docker_jhipster-registry_1_, you should see both networks and you should be able to authenticate against keycloak as well.
You can also do the reverse I believe, adding docker_default to keycloak container, but I would like just to point out where is the issue. It worked for me.

**Comment by mraible** [comment]
This configuration has changed for JHipster Registry 5.0.0. Can you try with the latest release?
