### ISSUE TITLE
Setup Travis for the registry

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#34]
Although the registry doesn't have a lot of code we should still setup Travis for it. It would help when upgrading dependencies.
What we could do:
- mvn package and launch the jar to see if there are errors
- generate a sample microservice and see if it can connect to the registry
- add config files and request them with the config server API

Any other ideas ?

**Comment by pascalgrimaud** [comment]
As the number of projects grow up in JHipster organization, should we use Travis in every project ?
I think about alternative, like CircleCI, drone.io (used in the past for sample projects)
Let's discuss

**Comment by PierreBesson** [comment]
I would be interested to try out codeship (https://codeship.com/) as it has Docker compose support but they say the free plan is limited to 100 builds. Is it per day ? total ? 
There is also Shippable (https://app.shippable.com/). It might be worth giving those "docker native" CI a try.

Also it would be interesting to have a docker registry in the CI infrastructure so that we don't have to rebuild images all the time. Maybe we can use Docker Hub for that but it seems that we would be overusing it.

TravisCI and CircleCI seem to be equivalent in terms of features. However I'm worried does Drone have support for docker ?

**Comment by pascalgrimaud** [comment]
I don't understand : what do you mean by rebuild image all the time ? Manually ?

About other CI, I only work with Travis and CircleCI. Never test codeship, shippable or drone.io

**Comment by PierreBesson** [comment]
Thinking about it more it might not apply to our case but I mean that when doing integration tests with multiple containers it might be interesting to have a local registry from which you can quickly pull the images you need.
