### ISSUE TITLE
Fix npm vulnerabilities

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-registry#347]
##### **Overview of the issue**

If you run `npm install` on this project, there's quite a few vulnerabilities:

```
found 966 vulnerabilities (467 low, 475 moderate, 24 high)
```

##### **Motivation for or Use Case**

We should not depend on vulnerable libraries.

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-registry/pull/392
