### ISSUE TITLE
Fix Docker Hub automated build tags

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#35]
ping @pascalgrimaud
Currently, the docker hub automated build is not correctly handling tags (see https://hub.docker.com/r/jhipster/jhipster-registry/builds/). 
What we would like to have is:

- jhipster-registry:latest -> get the latest tagged release of the registry
- jhipster-registry:v1.0.0 -> get the version explicitly tagged as 1.0.0
- jhipster-registry:master -> version from master

Also we when doing a release on github, it should create a new tag on docker-hub.

**Comment by pascalgrimaud** [comment]
Totally right.
We have a problem with trigger, between github and dockerhub.

I have to work with Julien for this, as he has full rights on github organization + dockerhub organization

**Comment by pascalgrimaud** [comment]
On Docker Hub, in **build settings**, I delete the type: tag + v1.0.0
So the tag v1.0.0 on docker hub won't be updated every commit/push

Don't worry, the tag v1.0.0 still exists => https://hub.docker.com/r/jhipster/jhipster-registry/tags/

**Comment by PierreBesson** [comment]
Thanks, that's a good decision for now.

**Comment by jdubois** [comment]
@pascalgrimaud is it working fine or do I need to do anything?

**Comment by pascalgrimaud** [comment]
@jdubois: it s not working as we would like => every tag doesnt trigger a docker build

For testing, can you:
- create a repo in Jhipster organization
- give full rights to Pierre and me

I will play on this repo, create branch, tag, etc...
Maybe I will need you later to add the trigger to Docker Hub, like we did for generator-jhipster and jhipster-registry

**Comment by jdubois** [comment]
@pascalgrimaud @PierreBesson you are now full admin of https://github.com/jhipster/test-docker-hub

-> tell me when you're done, so that I delete the repo

**Comment by pascalgrimaud** [comment]
Thanks!

**Comment by pascalgrimaud** [comment]
Good news!!! This repo works like we would like!
@PierreBesson : can you confirm it works plz ? Made some commit+push to this repo, then some release/tag

Here the configuration I made:

### Docker Hub
- create and link the repository to GitHub
- go build settings

**[x]** When active, builds will happen automatically on pushes.

| Type        | Name           | Dockerfile Location  | Docker Tag Name |
| ------------- |:-------------:| -----:| --------:|
| Branch      | master | / | master |
| Tag |  | / | latest |
| Tag |  | / |  |

Click on **Save Changes**

### Github
- go to settings > Webhooks & services
- verify these is **no webhook** => @jdubois we added some webhooks, so we have to delete them
- verify the services: Docker => edit
- click [x] active
- click on update service
- then, made a commit+push
- the service Docker must be :white_check_mark: Docker

**Comment by jdubois** [comment]
Great, is this urgent or not?
Next day I have some free time is April, 11th, and as @pascalgrimaud @PierreBesson you will both be at  the Ippon office in the evening, I guess it's safer to do those modifications on that day.

**Comment by pascalgrimaud** [comment]
not urgent :-)

**Comment by PierreBesson** [comment]
@pascalgrimaud, this is working great ! Thanks.

**Comment by pascalgrimaud** [comment]
Mhhh mhhh mhhh.. We forgot...

**Comment by jdubois** [comment]
Can you tell me what to do?
Can I delete the test repo I created for you?
Le 11 avr. 2016 11:13 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by pascalgrimaud** [comment]
@jdubois :
The automated build in Docker Hub should be correct.
The main issue is with github => we need to delete webhooks and need to update service with Docker. See my post https://github.com/jhipster/jhipster-registry/issues/35#issuecomment-203626119

**Comment by pascalgrimaud** [comment]
Plz keep the repo to compare the settings until everything is ok

**Comment by jdubois** [comment]
OK @pascalgrimaud I'm trying to correct this, first starting with the Console as less people use it.

**Comment by pascalgrimaud** [comment]
@jdubois : so does the configuration work ? Or did you have to trigger all dockerhub tags manually ?

**Comment by jdubois** [comment]
It was all automatic :-)

**Comment by pascalgrimaud** [comment]
Thanks @jdubois !!!
So the [test-docker-hub](https://github.com/jhipster/test-docker-hub) repo can be deleted I think
And this ticket can be closed
