### ISSUE TITLE
Release JHipster Registry 5.0.1

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-registry#353]
* [ ] Update dependencies in `package.json` and `pom.xml` to use the same versions JHipster 6 uses
* [ ] Change version in `pom.xml` and `package.json` to be `5.0.1`
* [ ] Update Docker Compose files in generator-jhipster to reference the new version

**Comment by jdubois** [comment]
Sorry @mraible I just released v5.0.0 and I missed this ticket -> I think it's all good, I did some testing this morning.

**Comment by jdubois** [comment]
Concerning the point in docker-compose.yml I also found the same issue (and that's good, we both found out the same config so it should be good!), and that should also be added to the Kubernetes configuration.

-> let me do this, I'm waiting to have the Docker Hub build of JHipster Registry 5.0.0 to finish, and I'll do this (so probably this evening)

**Comment by mraible** [comment]
Since this never got closed with 5.0.0, I updated it for 5.0.1. We should do a release because of https://github.com/jhipster/jhipster-registry/issues/356.

**Comment by pascalgrimaud** [comment]
@mraible : I'll take care of this release

**Comment by pascalgrimaud** [comment]
Done here: https://github.com/jhipster/jhipster-registry/commit/7281d2e0e780f3f42ba95bc670509e62843aa425

**Comment by pascalgrimaud** [comment]
I'm waiting the new version v5.0.1 at Docker Cloud, then, I'll update the version at generator-jhipster
