### ISSUE TITLE
OAuth2 does not work

### ISSUE THREAD

**Issue by aanno2** [jhipster/jhipster-registry#385]
I'm using jhipster-registry with a self-hosted keycloak. I have run v4.0.4 and v4.1.1 without problems in this scenario. 

However, I now want to update to v5.0.2 (I also tried master). When I try to login (jhipster-registry running with profile 'oauth2'). I always see: '[invalid_id_token]'. 

I spent a few minutes on debugging this. Code uses InMemoryDetailsManager with the only user filled in is admin/admin loaded from the configuration Yaml. So no wonder is does not work. Has anybody done at least minimal testing on the 'oauth2' profile?

**Comment by mraible** [comment]
Yes. I've tested it with both Keycloak and Okta. You can see it works in this screencast:

https://youtu.be/ez7HMO60kE8

**Comment by aanno2** [comment]
Well, I'm unconvinced. If I got the video right, you access jhipster-registry through jhipster-gateway (?!?). This is _not_ my useage scenario - I want to access jhipster-registry (ui) directly (and being redirected to OpenId/OAuth2 server in case I'm not logged in). Jhipster-registry v5.0.2 does not do this (but it has worked in v4.1.1). When I try to access jhipster-registry v5.0.2 directly, I always get an Html Page saying  '[invalid_id_token]'.

In addition to this, I have the following concerns:
* InMemoryDetailsManager is only for testing and must not be used in a production-ready application.
* There is a the user admin/admin loaded in the InMemoryDetailsManager at spring start (maybe only with 'dev' profile (?!?)). This is a complete no-go (and should happend only for testing).
* As far as I tested, the application uses the (default) FixedAuthoritiesExtractor. This is completly unsuited when using Keycloak, as it never gets the roles right.
* I'm unconvinced that the app has been tested with another user than admin/admin with the role(s) 'ROLE_ADMIN' created in Keycloak.

**Comment by mraible** [comment]
I access JHipster Registry directly, using port 8761. It redirects to Keycloak or Okta, depending on which one is configured.

**Comment by aanno2** [comment]
Well, I tried this several times and it has _not_ worked for me. But I will retry it again.

What about the other things I mentioned? Have you created another user in Keycloak with Role ROLE_ADMIN? Has this user been able to user the registry? Do you agree with having a 'automatic' user admin/admin is a security problem?

**Comment by pascalgrimaud** [comment]
it should work on the last version of registry
