### ISSUE TITLE
please support nacos configuration center

### ISSUE THREAD

**Issue by yudar1024** [jhipster/jhipster-registry#387]
##### **Overview of the issue**

please support nacos configuration center

##### **Motivation for or Use Case**
in most real case, microservice architect use nacos or appollo as configuration center.  git configuration center can not use product env.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
duplicate https://github.com/jhipster/generator-jhipster/issues/10597
