### ISSUE TITLE
DEBUG is enabled by default for io.github.jhipster

### ISSUE THREAD

**Issue by rainerh** [jhipster/jhipster-registry#393]
##### **Overview of the issue**

Current log settings 'pollutes' the log files with many DEBUG messages.

##### **Motivation for or Use Case**

Lots of DEBUG messages in the log files

##### **Suggest a Fix**

src/main/resources/logback-spring.xml contains the following DEBUG logger configuration:
`<logger name="io.github.jhipster" level="DEBUG"/>`

I'd propose to change it to:

`<logger name="io.github.jhipster" level="#logback.loglevel#"/>`

##### **JHipster Registry Version(s)**

v5.0.2

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
I agree with you that it's actually not a good practice at all.

**Comment by DanielFran** [comment]
Close via #392
