### ISSUE TITLE
Remove "Deploy to Heroku" button

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#397]
The feature is unmaintained and an additional burden to keep because of the master/develop branch separation.

**Comment by jdubois** [comment]
You need to check with @jkutner because I believe he maintains it.
But yes we should focus on having a great Docker image that could be deployed anywhere (including Heroku) with little effort.

**Comment by PierreBesson** [comment]
I already ping him with no answer a week ago [jhipster/jhipster-registry/pull/395#issuecomment-559491625](https://github.com/jhipster/jhipster-registry/pull/395#issuecomment-559491625).
In the end, using this button doesn't fit into any development workflow that I know of and also we focus more on docker and kubernetes.

**Comment by mraible** [comment]
I used it a couple years ago and it worked great. Also, this Heroku article that Julien wrote uses it. I think it's a slick feature.

https://blog.heroku.com/bootstrapping_your_microservices_architecture_with_jhipster_and_spring

**Comment by PierreBesson** [comment]
This article is from 2016

**Comment by mraible** [comment]
True. But I wrote one in 2018 and used the same button. It worked fine. 

https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth#deploy-to-heroku <https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth#deploy-to-heroku>

Why remove something that works? If it doesn’t work, that’s a different story.

**Comment by jkutner** [comment]
@PierreBesson where you expecting a response from me on https://github.com/jhipster/jhipster-registry/pull/395#issuecomment-559491625?

**Comment by jkutner** [comment]
@PierreBesson my change in role at Heroku has no bearing on my ability to support the JHipster Heroku integration.

**Comment by PierreBesson** [comment]
That's good to hear @jkutner :smiley:. I did not expect such a strong support for this feature. I am reconsidering my idea. Let's keep this.

**Comment by PierreBesson** [comment]
Sorry I thought I had asked you directly.

**Comment by jkutner** [comment]
@PierreBesson what master/develop branch thing are you talking about? The Heroku Button uses a buildpack pulls in the latest release:
https://github.com/jhipster/jhipster-registry-buildpack/blob/master/bin/compile#L19

**Comment by PierreBesson** [comment]
Oh really ! I think everyone including @jdubois @pascalgrimaud were under the impression that we must not merge  jhipster registry PRs into master before the release in fear of breaking the heroku button. So it seems this is no longer the case right now. Thanks!

**Comment by jkutner** [comment]
@PierreBesson oh, that may have been true a few years ago. probably my bad for not making it clear that things had changed.

**Comment by SudharakaP** [comment]
Hey everyone; I think this is the same thing with the GCP button; #395; After we resolve those problems in the GCP button side I think we can add it without effecting Heroku or creating separate branches. Is this something you guys are interested in? 😄

**Comment by PierreBesson** [comment]
Yes @SudharakaP please open an issue.

**Comment by pascalgrimaud** [comment]
it means we don't need develop branch anymore. So let's work on the Registry and delete the develop branch once everything is merged, specially the migration to JH 6.5.0
