### ISSUE TITLE
Releases of v6.0.0 and v6.0.1 don't show in releases page

### ISSUE THREAD

**Issue by yotamshapira** [jhipster/jhipster-registry#403]
##### **Overview of the issue**

Hi,

The releases page ( https://github.com/jhipster/jhipster-registry/releases ) shows that the latest release is v5.0.2 . However, tags for v6.0.0 and for v6.0.1 are also shown, but not as official releases. From my personal experience, this is caused by deleting releases from the releases page.
Are these officially released versions? If so, is it possible to set them as "regular" releases?

##### **Motivation for or Use Case**

Clarity for consumers.

##### **Reproduce the error**

N/A

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Registry Version(s)**

6.0.0 & 6.0.1

##### **Browsers and Operating System**

N/A

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I didn't do it yet, as there is no official release of generator-jhipster, which uses jhipster-registry v6.0.1
So for now, no official release, but feel free to test it and give feedback

**Comment by pascalgrimaud** [comment]
It should be good at https://github.com/jhipster/jhipster-registry/releases/tag/v6.0.2
