### ISSUE TITLE
Error when Using the pre-packaged JAR file version 6.0.2

### ISSUE THREAD

**Issue by JeremieLapert** [jhipster/jhipster-registry#414]
##### **Overview of the issue**
I download JHipster Registry executable on this [ Releases page](https://github.com/jhipster/jhipster-registry/releases) .

I follow the documentation about [JHipster Registry](https://www.jhipster.tech/jhipster-registry/) and when i try to run the jar, i obtain this error :
`zsh: erreur de format pour exec(): ./jhipster-registry-6.0.2.jar`

However, when i run :
```
java -jar jhipster-registry-6.0.2.jar
```
the jhipster-registry app starts

##### **Motivation for or Use Case**
This issue is important because it's a regression from previous version and because the documentation isn't up to date.

##### **Reproduce the error**
Run this command :

`./jhipster-registry-6.0.2.jar --spring.profiles.active=prod --spring.security.user.password=admin --jhipster.security.authentication.jwt.secret=my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded --spring.cloud.config.server.composite.0.type=git --spring.cloud.config.server.composite.0.uri=https://github.com/jhipster/jhipster-registry-sample-config`

##### **Suggest a Fix**
I suggest to add :
```
<executable>true</executable>
```
like this
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <mainClass>${start-class}</mainClass>
        <fork>true</fork>
        <executable>true</executable>
        <!--
        Enable the line below to have remote debugging of your application on port 5005                 <jvmArguments>agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</jvmArguments>
        -->
    </configuration>
</plugin>

```

##### **JHipster Registry Version(s)**
This issue is a regression in v6.0.2 because this is functional in v5.0.2

**Comment by SudharakaP** [comment]
This is due to our removal of the executable jar by default; https://github.com/jhipster/generator-jhipster/issues/10255

@saturnism @PierreBesson : I think we should change the documentation and keep the non-executable jar as it is since there's a possibility that a user might want to deploy the registry using buildpacks? :thinking:  Let me know if you disagree. :smile:
