### ISSUE TITLE
Current master branch is throwing an error.

### ISSUE THREAD

**Issue by hmenorjr** [jhipster/jhipster-registry#418]
##### **Overview of the issue**

Recently cloned a new one on my local. When executing `./mvnw` it throws the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jhipster-registry: Fatal error compiling: release version 11 not supported -> [Help 1]
```
JHipster-registry is the same version which is 
```
[INFO] -----------< io.github.jhipster.registry:jhipster-registry >------------
[INFO] Building JHipster Registry 6.0.2
[INFO] --------------------------------[ jar ]---------------------------------
```

##### **Motivation for or Use Case**

Using this for a microservice web application I'm building

##### **Reproduce the error**

1. Create a microservice gateway by executing `jhipster` on the gateway folder.
2. Execute `git clone git@github.com:jhipster/jhipster-registry.git` outside the gateway folder

##### **Related issues**

N/A

##### **Suggest a Fix**

Remove the previous commits.

##### **JHipster Registry Version(s)**

6.0.2 on `master` branch

##### **Browsers and Operating System**

OS: MacOS Catalina
Browser: Firefox 72.0.1 (64-bit); Chrome Version 79.0.3945.117 (Official Build) (64-bit)

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@hmenorjr : Did you try setting JAVA_HOME ? :smile: 

https://stackoverflow.com/questions/51631346/maven-3-8-0-compiler-fatal-error-compiling-release-version-11-not-supported

**Comment by ruddell** [comment]
Kind of related, it also doesn't work out-of-the-box for Java 8.  I had to change the `<java.version>11</java.version>` to `<java.version>8</java.version>` and remove `<release>${java.version}</release>` from the `maven-compiler-plugin` configuration to get it to start up.

**Comment by pascalgrimaud** [comment]
Well, I understand the issue as this project needs Java11 and it isn't mentionned. Anyway, we will remove the support of Java8 very soon in all our JHipster projects, as it requires a lot of work / tests to support both.
So I suggest you to upgrade to Java11.

**Comment by juliensadaoui** [comment]
I'm sorry. I decided that the baseline version is Java 11. All our build with the jhipster registry are executed with AdoptOpenJDK 11. We can't guarantee it works with Java 8 ...

**Comment by pascalgrimaud** [comment]
I think we can close this, as you need to use Java 11 to build.

**Comment by hmenorjr** [comment]
Thanks for the update guys. I'll inform my developers to update OpenJDK11 if management decides to push with the JHipster route.
