### ISSUE TITLE
Links for logs and loggers are incorrect

### ISSUE THREAD

**Issue by sazeez** [jhipster/jhipster-registry#422]
##### **Overview of the issue**
Links for logs and loggers seem to be swapped. When clicking on logs, the logger screen is displayed and vice-versa.

##### **Motivation for or Use Case**
The links should display information per navigation bar.

##### **Reproduce the error**
I checkout v6.0.2 tag from github, and ran jHipster in development mode (./mvnw -Pdev,webpack). 

##### **Related issues**
None that I could find.

##### **Suggest a Fix**
Index: src/main/webapp/app/layouts/navbar/navbar.component.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/webapp/app/layouts/navbar/navbar.component.html	(revision c6e8a17a35495d7487af6781d0e35bc9b7844205)
+++ src/main/webapp/app/layouts/navbar/navbar.component.html	(date 1580433952757)
@@ -103,7 +103,7 @@
                         </a>
                     </li>
                     <li>
-                        <a class="dropdown-item" routerLink="admin/logs" routerLinkActive="active" (click)="collapseNavbar()">
+                        <a class="dropdown-item" routerLink="admin/logfile" routerLinkActive="active" (click)="collapseNavbar()">
                             <fa-icon icon="file-alt" [fixedWidth]="true"></fa-icon>
                             <span>Logs</span>
                         </a>
@@ -115,7 +115,7 @@
                         </a>
                     </li>
                     <li>
-                        <a class="dropdown-item" routerLink="admin/logfile" routerLinkActive="active" (click)="collapseNavbar()">
+                        <a class="dropdown-item" routerLink="admin/logs" routerLinkActive="active" (click)="collapseNavbar()">
                             <fa-icon icon="tasks" [fixedWidth]="true"></fa-icon>
                             <span>Loggers</span>
                         </a>

##### **JHipster Registry Version(s)**
v6.0.2

##### **Browsers and Operating System**
Chrome, MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by juliensadaoui** [comment]
I confirm it !
This is a bug introduced by this ticket #391 

I synchronized the registry with jhipster 6.5.0, links for logs and loggers have been overwritten
