### ISSUE TITLE
Python client

### ISSUE THREAD

**Issue by unikzforce** [jhipster/jhipster-registry#430]
Is it possible for you guys provide a way to register python services on jhipster-registry?
##### **Overview of the issue**
I couldn't connect with eureka python clients in the github to the jhipster registry, because of the extra authentication that it has and no library in the github cant't handle `admin:admin@some-registry` .  In the microservices environment it's very usual to be polyglot, at least python is something many people use as a separate microservice especially the ML guys use it. please help me with this one.

##### **Browsers and Operating System**

- [ +] Checking this box is mandatory (this is just to show you read everything)

**Comment by unikzforce** [comment]
I want to create a python client for jhipster registry based on an open source python eureka client.. Would you guys please guide me? What are the additional steps that are needed ti be added to an standard eureka client so it could communicate correctly with jhipster-registry..
I want to create a PR for this client:
https://github.com/keijack/python-eureka-client

**Comment by gmarziou** [comment]
our library already support basic authentication; https://github.com/keijack/python-eureka-client/blob/master/py_eureka_client/http_client.py#L24

**Comment by unikzforce** [comment]
sorry , It was just a silly mistake, I'll close the Issue now
