### ISSUE TITLE
jhipster-registry not starting when using vault as config backend

### ISSUE THREAD

**Issue by indiepopart** [jhipster/jhipster-registry#433]
**Overview of the issue**

Adding vault as a config server backend with config.server.bootstrap=true makes the registry fail on start.

**Reproduce the error**
In a JHipster microservices architecture with docker deployment, add the following environment vars to jhipster-registry.yml:
```yml
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_SEARCH_LOCATIONS=file:./central-config
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=vault
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_HOST=localhost
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_PORT=8200
```
Exception:
```
jhipster-registry_1   | java.lang.IllegalStateException: No HttpServletRequest available
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.HttpRequestConfigTokenProvider.getToken(HttpRequestConfigTokenProvider.java:41)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.VaultEnvironmentRepository.getToken(VaultEnvironmentRepository.java:118)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.VaultEnvironmentRepository.read(VaultEnvironmentRepository.java:109)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.AbstractVaultEnvironmentRepository.findOne(AbstractVaultEnvironmentRepository.java:88)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.EnvironmentRepository.findOne(EnvironmentRepository.java:31)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.CompositeEnvironmentRepository.findOne(CompositeEnvironmentRepository.java:66)
jhipster-registry_1   | 	at org.springframework.cloud.config.server.environment.EnvironmentRepositoryPropertySourceLocator.locate(EnvironmentRepositoryPropertySourceLocator.java:55)
jhipster-registry_1   | 	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
jhipster-registry_1   | 	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
jhipster-registry_1   | 	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:101)
jhipster-registry_1   | 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
jhipster-registry_1   | 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
jhipster-registry_1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
jhipster-registry_1   | 	at io.github.jhipster.registry.JHipsterRegistryApp.main(JHipsterRegistryApp.java:71)
jhipster-registry_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jhipster-registry_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jhipster-registry_1   | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jhipster-registry_1   | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
jhipster-registry_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
jhipster-registry_1   | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
jhipster-registry_1   | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

```

**Related issues**

The issue has been reported in spring-cloud-config and it is supposed to be fixed, but the intended setup described in #1485 is not working.
[Config Server using GitHub AND Vault AND bootstrap = true not working #1485](https://github.com/spring-cloud/spring-cloud-config/issues/1485)
[Made sure configTokenProvider default bean will be overridden by more specific versions. Fixing Issue #1485 #1537](https://github.com/spring-cloud/spring-cloud-config/pull/1537)

**JHipster Registry Version(s)**

6.1.2

**Comment by mraible** [comment]
I've added a bug bounty to this because I'd like to use Vault with JHipster Registry too!

**Comment by sanketrk** [comment]
Any updates on progress or is it being taken up?

**Comment by pascalgrimaud** [comment]
@sanketrk : no comment, so no progress I think. Don't hesitate to help here if you know what to do

**Comment by slpbaby** [comment]
I refer to [FWinkler79 Sample Project Setup](https://github.com/FWinkler79/SpringCloudPlatform/blob/Issue-SpringCloudConfigVaultBootstrap-Analysis/config-server/src/main/resources/bootstrap.yml) and is able to start the jhispter-registry. 
However, I was starting jhipster-registry directly from source instead of using docker because somehow my docker keep refused to connect to the vault port.

It seems like missing the configurations for spring.cloud.config.server.vault.authentication and spring.cloud.config.server.vault.token.

Below is the bootstrap.yml part I added for vault configuration.


    config:
      server:
        vault:
            authentication: TOKEN
            token: <My Token Here>
        bootstrap: true
        composite:
          - type: native
            search-locations: file:./central-config
          - type: vault
            host: localhost
            port: 8200

**Comment by slpbaby** [comment]
I have tested jhipster registry docker deployment (v6.3.0) with following environment vars and the jhipster-registry are working fine:

```
      - SPRING_CLOUD_CONFIG_SERVER_VAULT_AUTHENTICATION=TOKEN
      - SPRING_CLOUD_CONFIG_SERVER_VAULT_TOKEN=<my token>
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=vault
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_HOST=host.docker.internal
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_PORT=8200
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_1_SEARCH_LOCATIONS=file:./central-config
```

**Comment by pascalgrimaud** [comment]
yes, we could add:
- dockerized vault
- new profile vault

The important thing to do is to document it, after that

**Comment by mraible** [comment]
I increased the bug bounty on this issue to increase motivation. 😊
