### ISSUE TITLE
JHipster Registry does not work under non-root URL

### ISSUE THREAD

**Issue by mrts** [jhipster/jhipster-registry#436]
##### **Overview of the issue**

When I run JHipster Registry with Apache reverse proxy under a non-root HTTPS URL with the following configuration:

```
    <Location /registry/>
	ProxyPreserveHost On
        ProxyPass http://localhost:8761/
        ProxyPassReverse http://localhost:8761/
    </Location>
```

and open _website/registry/_ in browser, then I see an error page with title _An error has occurred :-(_.

When I open developer console, then I see that the application tries to load `website/main.d349279b7460a1b83d46.css` and `app/polyfills.179e8897ba212fa04403.bundle.js` resources from root URL. These are obviously not found as they are only available under `/registry/`.

##### **Motivation for or Use Case**

I want to run JHipster Registry behind a secure TLS terminating reverse proxy as the default HTTP connection is insecure. I need to use non-root URL as the main application is already running on the root URL.

##### **Reproduce the error**

1. Run JHipster Registry with standard settings
1. Configure Apache reverse proxy as described under _Overview_ and restart
1. Open _website/registry/_ in browser

**Expected**: JHipster Registry front page opens  
**Actual**: error page with title _An error has occurred :-(_.

##### **JHipster Registry Version(s)**

JHipster Registry version 6.1.2

##### **Browsers and Operating System**

Server is Ubuntu 18.04 with Apache 2.4.29, client browser is Chrome in Windows 10.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Have you tried configuring the baseHref to `/registry/`?  Related code is here: https://github.com/jhipster/jhipster-registry/blob/785fba92d6b4ddbb3130e70f962228edd14583b7/webpack/webpack.common.js#L91

**Comment by mrts** [comment]
Thanks for the tip! I'm running JHipster Registry with Docker Compose. Can we make `baseHref` to honor an environment variable, let's say `JHIPSTER_REGISTRY_BASEHREF` so that I can get it working by setting it in `docker-compose.yml`?

**Comment by ruddell** [comment]
The base href config is applied when the frontend is built (during packaging), so I don't think it's possible to use a docker-compose environment variable.

You can build your own docker image though, by cloning the repository, making your change, and running the following command from the root:

    docker build -t your-custom-tag .

**Comment by mrts** [comment]
Ah, right, makes sense! OK, I'll proceed as you suggested.
