### ISSUE TITLE
Looking at microservice metrics with OAuth causes login prompt and infinite loop

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-registry#439]
##### **Overview of the issue**

If you try to look at microservice metrics from JHipster Registry (when using OAuth for auth), it results in an infinite cycle where you're prompted to login and you can't make it go away.

##### **Motivation for or Use Case**

You should be able to see metrics from other services. 

##### **Reproduce the error**

Create a microservices architecture with the following JDL. Start all required containers (JHipster Registry and Keycloak) from the gateway, Start MongoDB for the store, then start all apps. Try to look at the metrics in JHipster Registry for the store app and you'll see the issue.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}

// will be created under 'kubernetes' folder
deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

##### **JHipster Registry Version(s)**

6.2.0

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mraible : I manage to reproduce the issue, but I can explain why:
- you start the registry inside a Docker container
- you start your apps directly from your folders
- then, the registry can't access to your app: inside Docker -> your apps

The reason is your Registry (which is inside Docker) can't access to your apps (which started in default host).
Then, the problem is:
- the API got a 401 error when calling the other microservice, so it is considered as not authenticated
- then redirect to Keycloak, which says you're already authenticated, so redirect to your app, and try to call again the API
- etc...

To avoid this:

1) start all your app inside Docker
2) start the registry directly from your folder instead of Docker

Another solution:
- change the behavior of the registry, and don't redirect automatically to Keycloak

To resume, the problem comes from Network between Docker and your hosts.

cc @juliensadaoui : I think you already encountered this. Do you confirm ?

**Comment by mraible** [comment]
You're right and your answer makes sense. Can you clarify how to do this?

> start the registry directly from your folder instead of Docker

**Comment by pascalgrimaud** [comment]
@mraible : 
- clone jhipster-registry
- go inside
- launch it with oauth2 profile

**Comment by mraible** [comment]
I experienced this again today in my JHipster 7 microservices demo.

**Comment by pascalgrimaud** [comment]
Is there a video or something else, to see the exact workflow you used ?

**Comment by mraible** [comment]
Yes. See
https://youtu.be/AG4z18qePEw

**Comment by pascalgrimaud** [comment]
Ok @mraible : I explained the behavior here https://github.com/jhipster/jhipster-registry/issues/439#issuecomment-631992094

To resume, the following workflows work:
- start locally registry + start locally microservice
- start locally registry + start microservice inside docker
- start registry inside docker + start microservice inside docker

This workflow doesn't work:
- start registry inside docker + start locally microservice

But I agree it should not be an infinite loop, as it's pretty bad

**Comment by pascalgrimaud** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/31963
