### ISSUE TITLE
Heroku button on Docker Hub doesn't work

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#47]
When using the Heroku button on https://hub.docker.com/r/jhipster/jhipster-registry/
The redirection didn't work:
> A valid GitHub directory could not be found.
> The given URL (https://hub.docker.com/r/jhipster/jhipster-registry/) is not a valid GitHub repository.

@jkutner any idea to make this button working both: on github and on docker hub ?

**Comment by jdubois** [comment]
I corrected it directly in the UI
