### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by rgordeev** [jhipster/jhipster-registry#471]
There is a mistake in the following documentation 
[https://www.jhipster.tech/jhipster-registry/](https://www.jhipster.tech/jhipster-registry/)
```
Using Docker

If you’d rather run the JHipster Registry from a Docker image, it is available on Docker Hub at jhipster/jhipster-registry. A docker-compose file to run this image is already present within each microservice src/main/docker directory:

    run docker-compose -f src/main/docker/jhipster-registry.yml up to start the JHipster Registry. It will be available on port 8761 of your Docker host, so if it runs on your machine it should be at http://127.0.0.1:8761/.

Please read our Docker Compose documentation for more information on using the JHipster Registry with Docker Compose.
```
There is no any docker-compose by the path `src/main/docker/jhipster-registry.yml`

**Comment by SudharakaP** [comment]
@rgordeev : Note that the line says `...is already present within each microservice src/main/docker directory...`. So when you generate a microservice application you have to look for that file within the micro-service `src/main/docker` directory. And also you have to choose `JHipster Registry` for the prompt, `Which service discovery server do you want to use?`.
