### ISSUE TITLE
Support  openapi 3 json

### ISSUE THREAD

**Issue by rainoko** [jhipster/jhipster-registry#472]
##### **Overview of the issue**

API first allows generate API from openapi version 3. Even though we can modify application so that /api-docs serve v3 json, registry doesn't correctly change api location url and therefor broke swagger UI functionality

##### **Motivation for or Use Case**

OpenAPI V3 gives many new features to describe API. Like api versioning with headers. and different models associated with these headers. It would be nice if registry can handle more than just swagger 2.0 json.

**Comment by juliensadaoui** [comment]
I'm OK to do that

**Comment by gmarziou** [comment]
Not sure you can do it now, it has been implemented in generator-jhipster v7 on main branch but depends on jhipster lib which is not yet released.

**Comment by pascalgrimaud** [comment]
@juliensadaoui @gmarziou : for your information, with @DanielFran, we plan to do a release of [jhipster-bom](https://github.com/jhipster/jhipster-bom) this afternoon.

**Comment by gmarziou** [comment]
Excellent, I did not know whether you wanted to have 2 parallel versions of jhipster lib in maven central. So the new one will be 3.10.0 but will only work with app genareted by JHipster 7? And 3.9.x will be for JHipster 6?

**Comment by DanielFran** [comment]
@gmarziou 
The new jhipster-bom project will create a new dependency under groupId tech.jhipster (instead of current io.github.jhipster).
We will start with version 0.1.0 this afternoon and deliver version 1.0.0 with jhipster 7.

The old jhipster will be deprecated and serve only V6.

**Comment by pascalgrimaud** [comment]
@gmarziou : not exactly.

Current project jhipster will not be maintained anymore, and the last release is still 3.9.0, for v6 projects. The package name is io.github.jhipster

The new project jhipster-bom, will be for v7. The release version will start with 0.1.0, with package name tech.jhipster
Just before v7 release, I'll do a new release 1.0.0

I don't know if you will be able to use 0.1.0, as it's compatible with Spring Boot 2.3

**Comment by pascalgrimaud** [comment]
ahha commented as same time, we're sync :)

**Comment by gmarziou** [comment]
Thanks to both :) I'm already in SB 2.3 so it should be fine.

**Comment by juliensadaoui** [comment]
Close via #503
