### ISSUE TITLE
can not build 6.3.0

### ISSUE THREAD

**Issue by vividcore** [jhipster/jhipster-registry#475]
##### **Overview of the issue**

after download 6.3.0 and try the step seperately both encounter error,but can wrok with 6.1.2

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jhipster-registry: Fatal error compiling: invalid flag: --release -> [Help 1]

1)mvn clean package -Pprod,war
2)first start up frontside with:npm start,then start up the backend with:mvn

the build evn as below,
jdk8 _202 
maven 3.6.2
npm:6.13.7
node:13.10.1

**Comment by gmarziou** [comment]
Very likely related to JDK version, see #474

**Comment by vividcore** [comment]
for those who still wants to support jdk8 l made below changes,
1)change the <java.version>11</java.version> to <java.version>8</java.version>
2)remove <release>${java.version}</release>

above chanegs can support my project.
