### ISSUE TITLE
gateway with react  run "mvn -Pdev,webpack"  but "node_modules/@types/enzyme/index.d.ts(732,69): [INFO] TS2304: Cannot find name 'Cheerio'."

### ISSUE THREAD

**Issue by jieme198902** [jhipster/jhipster-registry#478]
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Fixed in https://github.com/jhipster/generator-jhipster/pull/12664

Workaround until patch release is to update `@types/enzyme` version in package.json:

```
"@types/enzyme": "3.10.7",
```
