### ISSUE TITLE
Improve "configuration" screen

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-registry#49]
This screen could have the following useful features:
- [x] Configuration source type: either git or filesystem (native profile)
- [x] Label : master by default (only with git ?)
- [x] Config source URI: either git or filesystem with the specified search-path
- [x] Autocompletion
- [ ] Instruction for setting up a git with username/password (similar to the instruction in the ssh screen)
- [ ] Read the application, profile and label from the URL hash (routes) so that we can link to it from the apps startup logs

**Comment by jdubois** [comment]
Closing as this has been opened for a long time, and no work is happening
