### ISSUE TITLE
Cannot deploy 6.4 to Heroku, release missing artifact

### ISSUE THREAD

**Issue by neilgrewal** [jhipster/jhipster-registry#490]
##### **Overview of the issue**

Cant deploy 6.4 to heroku

##### **Reproduce the error**

Deploy with any name using version 6.4

##### **Suggest a Fix**

Include the release jar artifact with the release like previous releases

##### **JHipster Registry Version(s)**

6.4

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/jhipster-registry/pull/491
