### ISSUE TITLE
Jhipster registry cannot start in Docker M1

### ISSUE THREAD

**Issue by thapatwat** [jhipster/jhipster-registry#500]
##### **Jhipster registry cannot start in Docker M1**
As I mention on title ,I used Registry image version: v6.3.0 in docker hub. Monitor log has show error as below when I start docker container
<img width="1440" alt="Screen Shot 2564-06-07 at 21 24 59" src="https://user-images.githubusercontent.com/85997637/122212333-e925fe00-ced1-11eb-9c14-b0ef2dccf308.png">

I'm not sure is that your problem, Docker side or I did something wrong.
Please answer me if you guy know how to solve this issue. Thank you

**Comment by gmarziou** [comment]
I'm not sure someone in the JHipster team owns a MacBook M1.

**Comment by jdubois** [comment]
We bought some for some team members, typically for this use case (ping @pascalgrimaud ).

**Comment by pascalgrimaud** [comment]
yes, I think @DanielFran or @mshima can help to test here

**Comment by DanielFran** [comment]
Yes, not all images have ARM64 support: https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues

**Comment by mshima** [comment]
I can confirm the problem.
I think the fix is to provide a jhipster-registry container for `linux/arm64` platform.
I have successfully run from source and run a custom build docker image (it took almost 40m using `docker buildx build -t local-build .`).

@pascalgrimaud someone should take a look at docker cloud integration and try to enable `linux/arm64`, or we can switch to GitHub actions to publish docker images.
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by pascalgrimaud** [comment]
I can have a look at Docker Hub.
But in the meantime, we could simply document it, so the end user can build the image, as 40min is very long and can queue our CI

**Comment by mshima** [comment]
IMO 40min build is not a good alternative.
`./mvnw -ntp package jib:dockerBuild` generates a docker images, but it fails to load due to dependencies.
I suppose it's broken for every platform.

**Comment by pascalgrimaud** [comment]
Adding a bounty on this.
If there are several people who participated to this ticket, tell me, so I can increase the bounty for sharing

**Comment by mshima** [comment]
This is resolved now.
Arm64 image is published to docker https://hub.docker.com/r/jhipster/jhipster-registry/tags?page=1&ordering=last_updated.

**Comment by sang-w0o** [comment]
> This is resolved now. Arm64 image is published to docker https://hub.docker.com/r/jhipster/jhipster-registry/tags?page=1&ordering=last_updated.

Great!! Thank you for your information :)

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/52029

**Comment by pascalgrimaud** [comment]
@mshima : approved :)
