### ISSUE TITLE
401 Unauthorized - Cannot convert access token to JSON for UAA healthpoint check

### ISSUE THREAD

**Issue by bobcaprice** [jhipster/jhipster-registry#508]
##### **Overview of the issue**

We are using jhipster-registry 6.8.0 in a microservice environment and our application is working, although some features in the jhipster-registry web interface aren't working, apparently all with the same error message. I will use healthchecks with our UAA server as an example.

Going to administration - health and selecting the UAA server from the dropdown results in a 401 request, with 'cannot convert access token to JSON' in the response. We have configured the UAA server so that the health endpoint doesn't require authorization, but the fact that the access token is present (for logging into the jhipster registry) means the UAA service tries to decode it and fails, as it wasn't generated by the UAA service.

The only way around this problem that we can think of is making the UAA server responsible for managing auth/auth for the jhipster registry and therefore the only service that is generating tokens, therefore able to decode the bearer token (despite not needing to for health checks). Is there a way of doing this? 

We have tried generating fresh UAA services using the jhipster generator 6.8.0 and running with the jhipster registry jar as directed in the jhipster registry docs and get the same problem.

##### **JHipster Registry Version(s)**

6.8.0

##### **Browsers and Operating System**

Latest version of chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by bobcaprice** [comment]
Any idea about this?

**Comment by mraible** [comment]
UAA support was dropped in JHipster 7.0.0. https://www.jhipster.tech/2021/03/21/jhipster-release-7.0.0.html

Maybe this has something to do with it?

**Comment by pascalgrimaud** [comment]
UAA was removed since JHipster Registry v6.7.0
If you want to use UAA with the JHipster Registry, I suggest you to:
- clone this project
- checkout v6.6.0
- fix the issues with UAA, as it was already broken at this old version
- maintain your own version in your fork

As there is no issue here, I'm closing this.
