### ISSUE TITLE
jhipster-registry can't be deployed in Tomcat 9.0.52

### ISSUE THREAD

**Issue by emeraldhieu** [jhipster/jhipster-registry#509]
##### **Overview of the issue**

jhipster-registry can't be accessed in standalone Tomcat 10.10.10

##### **Motivation for or Use Case**

https://www.jhipster.tech/production/ says jhipster-registry can be deployed using war file with a standalone Tomcat

##### **Reproduce the error**

- Checkout jhipster-registry
- Follow the guide at https://www.jhipster.tech/production
- Copy "jhipster-registry.war" into Tomcat's webapps
- Access http://localhost:8080/jhipster-registry
The page shows "HTTP Status 404 – Not Found"

##### **Related issues**

Can't find anything similar.

##### **Suggest a Fix**

I don't know.

##### **JHipster Registry Version(s)**

Branch "main". Revision "0f796f9145f1b6caec3d0449879cd00356dc8048".

##### **Browsers and Operating System**

MacOs. Chrome.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by juliensadaoui** [comment]
Duplicate issue #510
