### ISSUE TITLE
Add support for Auth0

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-registry#511]
##### **Overview of the issue**

https://github.com/jhipster/generator-jhipster/pull/15634 adds support for Auth0 to the main JHipster generator. It'd be cool if JHipster Registry supported it too.

##### **Motivation for or Use Case**

JHipster Registry works with Keycloak and Okta, so it'd be cool if it supported Auth0 too.

##### **Related issues**

https://github.com/jhipster/jhipster.github.io/pull/1151

**Comment by juliensadaoui** [comment]
I begun a working prototype with Auth0, will raise a PR the next week.
I can see my work in this [branch](https://github.com/juliensadaoui/jhipster-registry/tree/feat/511-oauth0-support)
