### ISSUE TITLE
Eureka can't resolve dns in kubernetes

### ISSUE THREAD

**Issue by greggameplayer** [jhipster/jhipster-registry#521]
##### **Overview of the issue**

I get this error every minute which said that there is a problem in the dns resolving.

In the jhipster-registry-0 pod it bugs on jhipster-registry-1 dns and in the jhipster-registry-1 pod it bugs on jhipster-registry-0 dns.

![image](https://user-images.githubusercontent.com/33609333/142737054-71b7ed68-cd23-47a3-8ef8-8a43141a83ed.png)

##### **JHipster Registry Version(s)**

7.1.0

**Comment by renanfranca** [comment]
@greggameplayer hello! I'm using Google cloud and I didn't face this error. I run locally with minikube and it works too

**Comment by greggameplayer** [comment]
Ok i've corrected it, it was just because in the generated jhipster-registry service, the part was named but on the container it wasn't named so i've put `targetPort: ` instead of name in the service
