### ISSUE TITLE
JHipster registry cannot connect to keycloak on a different server

### ISSUE THREAD

**Issue by yamennassif** [jhipster/jhipster-registry#534]
##### **Motivation for or Use Case**

I need to run keycloak on one server and registry on a different server

##### **Reproduce the error**

1- run keycloak on server A
2- nginx to reverse proxy keycloak on the same server A
3- run JHipster-registry on different server B
4- change SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI in jhipster-registry.yml to point to server A.

##### **JHipster Registry Version(s)**

v7.3.0

##### **Browsers and Operating System**

Linux and Windows.

##### **Error message**

 Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by juliensadaoui** [comment]
@yamennassif if this is still an issue please ask to reopen
