### ISSUE TITLE
[Feature] allow the Registry to do REST calls to management APIs of the apps

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#54]
The Registry could have a specific user/password that allows it to access the applications (microservices and gateway):
- It could be able to access the /health and /info endpoints, so it could display better information on the applications
- It could even have its admin UI point to the metrics, logs, configuration endpoints, so you could manage everything from the Registry

That means the Registry back-end would do REST requests to the applications, probably using the Spring REST template.

**Comment by jgoldhammer** [comment]
I have integrated https://github.com/codecentric/spring-boot-admin in my application and it works quite well. It provides an admin UI for all common actuator endpoints...

**Comment by magaton** [comment]
One problem I had with spring boot admin is after declaring it as pom dependency and enabling it, my zuul routes in eureka registered api-gateway are completely ignored. I would also prefer to have the mentioned health endpoints available in jhipster-registry. Any plans or suggestions what would be the best way to do that?

**Comment by jdubois** [comment]
I'm sorry @jgoldhammer @magaton but if you want to use Spring Boot Admin, then have a look at the Spring Boot Admin project, not JHipster....
I don't know if it works well with Zuul or the Registry, I haven't had a look at it at all.
I'm not going to use this project for 2 reasons:

- The naming and branding: it looks like an official Spring Boot project, which I thought it was at first, but it is not. Which means I don't really share the values of this project (but that's just a personal opinion), and that at some point in time they will have some licensing issues. And I don't want to have those issues pushed into JHipster.
- From what I see, they copied our screens. As long as those are the same screens, I'd much rather use ours. I know how they work much better, and I have full control on them, if something needs to be modified.

**Comment by magaton** [comment]
Clear, I am asking what would be the best way to expose /env and /metrics screen for each of the services running within jhipster-registry.

**Comment by jdubois** [comment]
That's my main question currently -> I'd use the Spring RestTemplate, but I haven't worked on it yet, maybe there's something easier or better

**Comment by PierreBesson** [comment]
I just got an idea. Ultimately what we want is to expose the management endpoint on the registry, so why not put a Zuul Proxy on the Registry.
This registry would be restricted to /management only (by making use of zuul filters). I think that it would be very useful to expose all those endpoints to the outside world somewhere (in a centralized place). Of course we should think about the security implications and there must be an option to disable the proxying...

We can even just put the swagger ui there and we can already call the management endpoints.

**Comment by jdubois** [comment]
@PierreBesson I just had exactly the same idea this morning - so great that we share the same office space, so we can exchange ideas on GitHub :-)
Yes let's do it that way.
-> having an independent admin UI could also be interesting for monolith apps. So this makes me wonder if we should migrate those screens to AngularJS 2 - but that's another issue, and I'll first start a discussion on this on the dev mailing list

**Comment by jdubois** [comment]
On second thoughts: most people use monoliths at the moment, and forcing them to use the Registry isn't probably a good idea, so let's keep it the way it is today for monoliths

**Comment by PierreBesson** [comment]
@jdubois I agree that we shouldn't force Monoliths to use the registry. But what we could do is create a "client module" (a component based on angular 2) publish this to npm, then reuse this "module" both in the monolith and in the registry. In the monolith it would query `/management/*` and in the registry it would query `/appX/management`.

**Comment by jdubois** [comment]
@PierreBesson yes, very good idea

**Comment by pascalgrimaud** [comment]
I think the idea very interesting.

On my project, we need to change the logs level of microservices, so we implemented this feature on the gateway, instead of registry.
The only problem is when we have X microservices, so we need to call the api X times.

But I think the best should be in the registry and not in the gateway

**Comment by jdubois** [comment]
Yes, it's better for security, etc... As our Angular 2 release is coming, work on this could start soon, if you're interested :-)

**Comment by jdubois** [comment]
I'm closing this to make a better, cleaner ticket for the next big version of the Registry!
