### ISSUE TITLE
Update registry to work with Keycloak v18.x onwards

### ISSUE THREAD

**Issue by vishal423** [jhipster/jhipster-registry#542]
##### **Overview of the issue**
Update JHipster Registry code to work with Keycloak v18.x onwards

##### **Motivation for or Use Case**
Keycloak v18.x introduced logout breaking changes to comply with OIDC spec. Logout doesn't work with current version of JHipster Registry

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Added a bug bounty to get this fixed.

**Comment by pascalgrimaud** [comment]
@juliensadaoui : can we close this?
