### ISSUE TITLE
Registry docker image requires JWT base64-secret in oauth2 profile

### ISSUE THREAD

**Issue by vishal423** [jhipster/jhipster-registry#543]
##### **Overview of the issue**
JWT base64-secret should not be mandatory in oauth2 profile

##### **Reproduce the error**
- Generate the JHipster application with OIDC authentication and select integration with JHipster Registry
- Start the Keycloak container
- Start `jhipster-registry` container -- `docker-compose -f src/main/docker/jhipster-registry up`
- You shall see startup errors due to the null `base64-secret` configuration required by TokenProvider. 
- Specify some dummy long base64-secret under `src/main/docker/central-server-config/localhost-config/application.yml` and start JHipster Registry again. This time you should see the registry starts up correctly.

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Added bug bounty to get this fixed.

**Comment by DanielFran** [comment]
@juliensadaoui Can we close this issue?
