### ISSUE TITLE
Maybe missing files/installations in Dockerfile

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#58]
I can see new files at root folder:
- bower.json
- package.json
- gulpfile.js
- and more..

There are maybe some issues:
- The [Dockerfile](https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile) to build the image only add these files: https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile#L6-L10
- there is no node, npm, bower, gulp installations inside the Dockerfile

=> we need to investigate a little bit to confirm the jhipster/jhipster-registry works well. Maybe it's possible with https://github.com/jhipster/jhipster-registry/blob/master/pom.xml#L330-L331

**Comment by PierreBesson** [comment]
@pascalgrimaud Actually, the registry docker image is actually serving the app in dev profile ! So npm is never used by the docker automated build :smile:.
If we added a -Pprod, it should do the full build, installing npm and bower, running protractor test, etc... However it doesn't minify the code.
https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile#L14 
Actually, I tried to add this:
```
+ADD package.json bower.json gulpfile.js /code/
 ...
-    ./mvnw package && \
+    ./mvnw package -Pprod && \
```
 but the front-end mvn plugin fails when doing the docker build.

I would be in favor of doing a full "-Pprod" build as this would fail the build in the docker hub and prevent shipping of a broken registry but it needs some work.

ping @jdubois.

**Comment by pascalgrimaud** [comment]
> but the front-end mvn plugin fails when doing the docker build.
Can you copy/paste the stack trace ? I will have a look tonight. If I remember the long discussion in generator-jhipster, this front-end mvn plugin is used in environment where node/npm is not installed, so it should work

**Comment by PierreBesson** [comment]
```
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ jhipster-registry ---
[INFO] Running 'npm install' in /code
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.044 s
[INFO] Finished at: 2016-05-17T08:30:51+00:00
[INFO] Final Memory: 28M/412M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project jhipster-registry: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "/code/node/node" (in directory "/code"): error=2, No such file or directory -> [Help 1]
[ERROR] 

```

**Comment by pascalgrimaud** [comment]
OK, I already encounter the same issue, but I don't remember when :smile: 
Same error here : https://github.com/eirslett/frontend-maven-plugin/issues/402
Ping @ddewaele : maybe you can help ?

About front-end-plugin:
Issue here : https://github.com/jhipster/generator-jhipster/issues/3356
PR here : https://github.com/jhipster/generator-jhipster/pull/3365

**Comment by jdubois** [comment]
Yes the Docker build is only in "dev" mode. For the registry, we don't really need to minify assets, etc, as it's only going to be used by very few people.
Of course if we could have a "prod" build it would be better, and as this is originally a JHipster application it shouldn't be too hard -> that's why I kept the gulp.js files, so we could do the "prod" build later.

I'm pretty sure the current image works well, I use it all the time. It's in dev mode, of course.

**Comment by PierreBesson** [comment]
@jdubois Fixing the prod build for the registry is going to be difficult because we are in an alpine environment. But if we manage to do it, it could even be possible to move to alpine for the `jhipster/jhipster` image.

**Comment by pascalgrimaud** [comment]
At the moment, I think the dev mode is enough, so we shouldn't lost time on this.
I opened this issue to point that the bower.json, package.json etc... are missing when building the Docker image.

**Comment by pascalgrimaud** [comment]
So we ll work on prod build later, no need it right now
