### ISSUE TITLE
jhipster-registry container cannot resolv names outside a stack on docker cloud

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-registry#59]
I did see this problem before and it occurs because of the image using to create the container. On generator-jhipster I had to move to java:8 instead of alpine.

Unfortunately the trade off is, my applications had 250MB using alpine, moving to java:8 it become to have more than 850MB!

The impact here is: jhipster-registry must be inside the stack you are going to create your gateways and applications and like in my case where the jhipster-console is in another stack it makes both blind of each other.

Stacks can help you organize your life and speed up your management mainly when you have many containers like monitoring, datastores, etc.

I think here, it is less an issue and more an advice about what happens using alpine on Docker Cloud for now.

**Comment by jdubois** [comment]
Are you talking about https://docs.docker.com/docker-cloud/apps/stacks/ ?

We currently only support Docker and Docker Compose, there is no notion of stack in what JHipster generates at the moment.

I don't understand why you would have a difference between Alpine and "java:8". Is that some kind of network issue, because you run different instances of Docker and you don't expose ports?

I haven't had those problems with our current setup, could you give me steps so I can reproduce it?

**Comment by marcelinobadin** [comment]
Yes, I am talking about those stacks... I know jhipster has no support for Docker Cloud and this is more like an advise for whom that want to use Docker Cloud.

The links concept we have on docker and docker-compose is different on Docker Cloud and Kubernetes, there those links are names resolved by the local DNS of your deployment.

On my tests deploying on Docker Cloud I found an issue with java:alpine, it does not have DNS support and it did cause some issues resolving names between applications. 

Now I am using Kubernetes but I had changed the image to java:8-jre (smaller than java:8) and I didn't change it back to see if there is the same issue on K8s.

@PierreBesson told me about this issue with java:alpine and we also tried the latest version on master to see if was issue solved but it was not. See [#3306 on generator-jhipster](https://github.com/jhipster/generator-jhipster/issues/3606)

Anyway, another share of my experience with Docker Cloud, it is simpler than Kubernetes but it is not reliable. I am using Kubernetes and it is much better, mainly speaking about data persistence but there are much more arguments to allow me to tell that Kubernetes was the best solution for my requirements to go to production which I am writing on an article that I would like to share with you as soon as I finish it.

**Comment by PierreBesson** [comment]
@marcelinobadin
Alpine 3.4 is now released: https://alpinelinux.org/posts/Alpine-3.4.0-released.html so it's just a matter of day before [`java:8-jre-alpine`](https://github.com/docker-library/openjdk/blob/8f8d04a5f77116be8ebfcaf84e4fcbd1190b95e8/8-jre/alpine/Dockerfile)  is upgraded too. 

Great that you are writing an article. I have not forgotten that we have planned to write some docs together. When you are ready to begin, please open

**Comment by jdubois** [comment]
Thanks for the feedback @marcelinobadin !!

- We have Kubernetes support out very soon
- Alpine Linux is now the default - I'm not sure about the DNS issue, is that OK for you? To me, we rely on standard Docker Compose features, and it "works on my machine", so Docker Cloud should support those

**Comment by marcelinobadin** [comment]
I am using Alpine since @PierreBesson told about the updates. It is working fine.

I'm also using Kubernetes for quite some time and that is the best for my requirements and easy to manage. By now, the only concern I have is to scale down. It scales up but I couldn't see it scaling down once the load drops. But also I didnt test it too much.

Cool, I will update things and start using JHipster Kubernetes support and if I have any feedback I will tell you.

I will take this opportunity to say sorry about my commitment to write some about my experience with other docker platforms but I am in a hurry and... well, sorry. Things finally are moving to production so priorities are priorities.

Anyway, here we go. Jhipster is awesome. Thanks.
