### ISSUE TITLE
"mvn -Pprod package" build failed

### ISSUE THREAD

**Issue by rainee007** [jhipster/jhipster-registry#61]
Used "mvn -e -X -Pprod package", got error below:
[INFO] [16:51:13] gulp-imagemin: Minified 0 images
[ERROR] fs.js:839
[ERROR]   return binding.lstat(pathModule._makeLong(path));
[ERROR]                  ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, lstat '/Users/renjun/ttt/jh/jhipster-registry/src/main/webapp/app/templates.js'
[ERROR]     at Error (native)
[ERROR]     at Object.fs.lstatSync (fs.js:839:18)
[ERROR]     at DestroyableTransform.TransformStream [as _transform] (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-header/index.js:38:12)
[ERROR]     at DestroyableTransform.Transform._read (/Users/renjun/ttt/jh/jhipster-registry/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at DestroyableTransform.Transform._write (/Users/renjun/ttt/jh/jhipster-registry/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite (/Users/renjun/ttt/jh/jhipster-registry/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
[ERROR]     at writeOrBuffer (/Users/renjun/ttt/jh/jhipster-registry/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
[ERROR]     at DestroyableTransform.Writable.write (/Users/renjun/ttt/jh/jhipster-registry/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
[ERROR]     at write (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[ERROR]     at flow (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[ERROR]     at DestroyableTransform.pipeOnReadable (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
[ERROR]     at emitNone (events.js:67:13)
[ERROR]     at DestroyableTransform.emit (events.js:166:7)
[ERROR]     at emitReadable_ (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
[ERROR]     at emitReadable (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
[ERROR]     at readableAddChunk (/Users/renjun/ttt/jh/jhipster-registry/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by PierreBesson** [comment]
We agree that the "prod" build is broken see: https://github.com/jhipster/jhipster-registry/issues/58
It is not a priority for us to fix it. However help on this matter would be very much appreciated, if you have the time.

**Comment by pascalgrimaud** [comment]
@rainee007 : can you try to update the lib in package.json `"gulp-angular-templatecache": "1.8.0"` -> `"gulp-angular-templatecache": "1.9.0"`

**Comment by rainee007** [comment]
@pascalgrimaud 👍 
It worked for me.

**Comment by pascalgrimaud** [comment]
can it be closed ?

**Comment by jdubois** [comment]
Sorry I missed this, thanks @pascalgrimaud !
