### ISSUE TITLE
Memory usage goes up

### ISSUE THREAD

**Issue by danielbrutti** [jhipster/jhipster-registry#63]
Hi,

I cloned the projects and trying to execute it over a linux machine. All containers are created just fine, I can see them with "docker ps" and look at usage with "docker stats".

However, memory keeps going up and up.. eventualy my laptop (core i5, 10gb RAM) stops responding and die!

I tried with mem_limit on each service definition on docker_compose.yml, and I can see the limit working on docker stats... however memory keeps going up and when the container gets > 95% usage it does dead... container stops working and is removed. So.. this setup just prevents my pc to die.. but nothing else.

I also tried with a JHipster project and set JAVA_OPTS for -Xmx and other memory parameters.. but the result is the same.

Can you please help me on this?

Thanks!

**Comment by danielbrutti** [comment]
Some examples of memory going up...

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e4d5c9f3433f        60.09%              191.3 MB / 536.9 MB   35.63%              8.952 kB / 648 B    0 B / 0 B           0
ec4897f6fe46        53.68%              157.7 MB / 536.9 MB   29.38%              8.862 kB / 648 B    0 B / 0 B           0
ca06afc1fcbb        43.09%              140.5 MB / 536.9 MB   26.18%              8.366 kB / 648 B    0 B / 0 B           0
04b456662588        38.39%              116.9 MB / 536.9 MB   21.77%              8.268 kB / 578 B    0 B / 0 B           0
58b615e2f1b5        40.14%              152.8 MB / 536.9 MB   28.46%              8.268 kB / 578 B    0 B / 0 B           0
33ee0ed8733b        51.45%              132.1 MB / 536.9 MB   24.60%              8.268 kB / 578 B    0 B / 0 B           0
094bdaa62c09        43.78%              132.8 MB / 536.9 MB   24.74%              7.305 kB / 578 B    0 B / 0 B           0
8fb94693b972        42.40%              116.8 MB / 536.9 MB   21.76%              6.817 kB / 578 B    0 B / 0 B           0





CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e4d5c9f3433f        48.01%              497.3 MB / 536.9 MB   92.62%              9.409 kB / 648 B    0 B / 0 B           0
ec4897f6fe46        50.45%              401.6 MB / 536.9 MB   74.80%              9.319 kB / 648 B    0 B / 0 B           0
ca06afc1fcbb        48.53%              344.9 MB / 536.9 MB   64.25%              8.893 kB / 648 B    0 B / 0 B           0
04b456662588        46.19%              361.4 MB / 536.9 MB   67.31%              8.725 kB / 648 B    0 B / 0 B           0
58b615e2f1b5        48.47%              354.9 MB / 536.9 MB   66.10%              8.725 kB / 648 B    0 B / 0 B           0
33ee0ed8733b        53.60%              356 MB / 536.9 MB     66.30%              8.725 kB / 648 B    0 B / 0 B           0
094bdaa62c09        48.87%              305.6 MB / 536.9 MB   56.93%              7.869 kB / 648 B    0 B / 0 B           0
8fb94693b972        45.19%              304.9 MB / 536.9 MB   56.78%              7.381 kB / 648 B    0 B / 0 B           0






eventually process starts to die...

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
ec4897f6fe46        58.48%              516.9 MB / 536.9 MB   96.27%              9.426 kB / 648 B    0 B / 0 B           0
58b615e2f1b5        58.96%              525.5 MB / 536.9 MB   97.89%              8.725 kB / 648 B    0 B / 0 B           0
094bdaa62c09        66.47%              446.1 MB / 536.9 MB   83.10%              7.869 kB / 648 B    0 B / 0 B           0
8fb94693b972        56.92%              376.7 MB / 536.9 MB   70.17%              7.381 kB / 648 B    0 B / 0 B           0

**Comment by jdubois** [comment]
You're posting this on the "registry" issue tracker, but I guess your containers run in fact JHipster applications, and you have this issue with JHipster applications?

- 500 MB of RAM doesn't look big to me -> for the Registry it's enough, but for a normal app it depends on what you do, but that's probably too small
- For a "normal" application, have a look at the ehcache configuration: this is using a off-heap cache, and in production its default value is 256M - this is a very small cache (most people should increase it), but your container has got so little RAM that it won't fit in memory

Then, you should indeed fix the JVM heap size and ehcache memory size -> if memory still grows, you have something else, and that probably depends on your OS, Docker version, etc...

As I don't think this is indeed related to the Registry I'm closing this as "incorrect", if your issue isn't solved can you re-open it on the generator-jhipster project and link it to this ticket? This is just to keep ticket systems clean.

**Comment by danielbrutti** [comment]
Hi, sure no problem.. I will re-open on generator-jhipster.
