### ISSUE TITLE
Dockerfile in dev

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#64]
Related to the discussion here : https://github.com/jhipster/generator-jhipster/issues/3791

This [Dockerfile](https://github.com/jhipster/jhipster-registry/blob/master/src/main/docker/dev/Dockerfile) need to be updated, to be consistent with the main [Dockerfile](https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile)

I will do this change, as soon as I can

**Comment by jdubois** [comment]
Closing as the PR is merged
