### ISSUE TITLE
Bootstrap offline

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-registry#65]
These 2 files contain a link to https://fonts.googleapis.com/css?family=Lato:400,700,400italic :
- https://github.com/jhipster/jhipster-registry/blob/master/src/main/webapp/bower_components/bootswatch-dist/css/bootstrap.css
- https://github.com/jhipster/jhipster-registry/blob/master/src/main/webapp/bower_components/bootswatch-dist/css/bootstrap.min.css

So when I deploy the registry on an environment which is offline, it doesn't work well.
What do you think about removing these links to google?

**Comment by deepu105** [comment]
May be we can ship the fonts from the contents folder

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
- I confirm the issue
- As this comes from Bootswatch, I don't think we can correct this - the fix must come from Bootswatch!

-> maybe you could open the ticket on Bootswatch, and link it here?

**Comment by pascalgrimaud** [comment]
There is already a ticket about this here: https://github.com/thomaspark/bootswatch/issues/55
So, different solutions:
- comment the line -> that's what we did on my project
- host the google font

As said, I don't think we can or should correct this
So I'm closing this, as there are solutions.
