### ISSUE TITLE
DiscoveryComposite - eureka	UNKNOWN

### ISSUE THREAD

**Issue by pdaniel-frk** [jhipster/jhipster-registry#69]
Hello,

I have a problem with eureka it seems. I start jhipster-registry. After I login to the interface i see a problem with DiscoveryComposite - eureka. The status is UNKNOWN.

![image](https://cloud.githubusercontent.com/assets/10430333/17119117/bdd21f9e-52cc-11e6-8868-c5a6d72f62ce.png)

Can someone explain me what this means?

**Comment by jdubois** [comment]
I'm having the same `unknown` label - those come directly from Spring Boot, we are just displaying what is being sent to us from the health endpoint.

- This should be OK, as I'm having the same label, and it's not a error message
- I'd love to know what this is, too -> this should be asked to the Spring Boot team

**Comment by pascalgrimaud** [comment]
**FYI** : I find the answer about the `unknown` label. You need to launch different `jhipster-registry` with the appropriate configuration -> the goal is to make an Eureka cluster

![eureka_discovery](https://cloud.githubusercontent.com/assets/9156882/20882312/92a2cfc2-bae0-11e6-940d-68bcb57b0c32.png)

**Comment by PierreBesson** [comment]
I confirm that the `unknown` label disappear when you set up a replica.
Here is what I did, first :
```
mvn package -Pprod
```

Then in two separate terminals :
```
java -jar target/jhipster-registry-2.5.5.war --spring.profiles.active=prod,peer1
java -jar target/jhipster-registry-2.5.5.war --spring.profiles.active=prod,peer2
```
I also needed to add this to my /etc/hosts
```
127.0.0.1	eureka-peer-1
127.0.0.1	eureka-peer-2
```
I guess this is quite complicated to setup, it would be nice to automate it with Kubernetes, maybe with a petset.

**Comment by jdubois** [comment]
That's quite logical, thanks @pascalgrimaud 
I wrote a documentation to have a cluster of registry, and it's available in the Web interface, can you have a look at it?
Then that could be a new option in our Docker Compose / Kubernetes sub-generators, to have a cluster of JHipster Registry if needed.

**Comment by pascalgrimaud** [comment]
@jdubois : yes I can have a look. Ping me when you push the documentation plz

@PierreBesson : you're right, it is not so easy, I'm working on this all this afternoon

**Comment by PierreBesson** [comment]
@pascalgrimaud, @jdubois is referring to this documentation in the replica tab of the jhipster console.
![capture d ecran 2016-12-05 a 16 51 12](https://cloud.githubusercontent.com/assets/513471/20893377/d967ec18-bb11-11e6-8da8-33b040ec61f3.png)

**Comment by pascalgrimaud** [comment]
oh! I didn't saw this button!!!
So yes, the documentation is correct ;-)

**Comment by jdubois** [comment]
Yes, the button isn't obvious :-)
I spent quite a lot of time to have this working fine!
