### ISSUE TITLE
DiscoveryComposite - eureka	UNKNOWN

### ISSUE THREAD

**Issue by pdaniel-frk** [jhipster/jhipster-registry#83]
When i start jhipster registry i get the attached error. Can someone know how to fix it?

![image](https://cloud.githubusercontent.com/assets/10430333/18616888/eceda570-7dcc-11e6-88c0-e213760c6ba8.png)

**Comment by pascalgrimaud** [comment]
You already asked it.
Look the answer: https://github.com/jhipster/jhipster-registry/issues/69

**Comment by jdubois** [comment]
???
I'm closing this as duplicate

**Comment by pdaniel-frk** [comment]
Yes, sorry. I haven't seen the answer.
