### ISSUE TITLE
How to  switch request traffic from old server instance to  a new one dynamically?

### ISSUE THREAD

**Issue by zongwu233** [jhipster/jhipster-registry#86]
when  I add new api and publish next version of a micro service , I need 
1. start a  new service instance
2. switch request traffic from old instance to the new one
3. remove / shut down old one 
And  I don't want to restart my gateway during these steps. Actually, I'm look  a runtime  dynamic routing method .

**Comment by jdubois** [comment]
This is a question on how Eureka works, not a bug on the project, could you open up a question on Stackoverflow instead?
