### ISSUE TITLE
[Question] Make a temporary config override for a specific application?

### ISSUE THREAD

**Issue by amr** [jhipster/jhipster-registry#87]
We deploy our microservices as well as jhipster registry using Docker.

Is there a way to make a temp change to one of the microservices that pull their configuration from jhipster registry without modifying the config in the central repo? Any of the following will work:

1. Environment variables (which I can set in `docker-compose.yml` for jhipster-registry and/or the microservices)
2. `curl -XPOST ...` to some jhipster registry endpoint

Or even something else.

**Comment by jdubois** [comment]
Environnement variables work, and look very easy to me (including with Docker), so that's probably the easiest solution.
