### ISSUE TITLE
how to  config high availability config-server

### ISSUE THREAD

**Issue by sakoojiang** [jhipster/jhipster-registry#92]
In config client:

the single node config-server configuration running ok:

      config:
         label: master
         name: config-client
         profile: dev
         uri: http://admin:admin@172.16.5.81:8761/config

but  when i config as discovery enable , the application run failed:
    
    spring:
      application:
        name: config-client    
        config:
          profile: dev
          label: master
          discovery:
            enabled: true                                
            serviceId: jhipster -registry(this is  the name JHipster  Registry  application)  
          name: config-client

    
    eureka:
        instance:
            prefer-ip-address: true
        client:
            enabled: true
            healthcheck:
                enabled: true
            registerWithEureka: true
            fetchRegistry: true
            serviceUrl:
                defaultZone: http://admin:admin@localhost:8761/eureka/

**Comment by jdubois** [comment]
I'm sorry but you give no version number, and no stacktrace, just that it "failed".
Besides, this is just a Spring Cloud configuration, I doubt there is any JHipster bug here -> this is the ticket system, we only solve bugs here. For help please use StackOverflow with the JHipster tag.

**Comment by samira2** [comment]
i have this problem too ,
when run my jhipster project i got following error : 

`java.lang.IllegalArgumentException: Could not resolve placeholder 'server.port' in value "${server.port}"`

my application.yml and application-dev.yml and application-prod.yml kept in my config server repositories and not in my jhipster project`
