### ISSUE TITLE
Upgrade the front-end to Angular 2

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#98]
This is linked to #97
Once the application is migrated to JHipster 4.x, the front-end should be upgraded from AngularJS 1 to Angular 2+

**Comment by mohamed2a** [comment]
This is the tasks list that we should fix : 

**First step**

- [ ] TypeScript integration
- [ ] Webpack integration
- [ ] Home page migration

**progress of individual module migrations**

- [ ] Application
- [ ] History
- [ ] Replicas
- [ ] Configuration
- [ ] SSH
- [ ] Admin:metrics
- [ ] Admin:health
- [ ] Admin:configuration
- [ ] Admin:logs

**Last item to migrate**

- [ ] Migration of Karma tests
- [ ] CSS Style adaptation

**Comment by deepu105** [comment]
@mohamed2a hope you will generate the app using JH4 and merge changes?

**Comment by mohamed2a** [comment]
Yes @deepu105

**Comment by pascalgrimaud** [comment]
@mohamed2a / @JulienMrgrd : will you work on a specific branch for that ? If yes, maybe should commit to a specific branch so we can review / test / help ?
Not sure if it should be 1 or 2 distinct branchs

**Comment by mohamed2a** [comment]
I think we will commit to "develop" branch very soon.

**Comment by JulienMrgrd** [comment]
Hi @pascalgrimaud and @deepu105.
I've already fork the registry, and creates 2 branches (for the front and the back migration) : 
https://github.com/JulienMrgrd/registry/tree/UpgradeJH4_Back
https://github.com/JulienMrgrd/registry/tree/UpgradeJH4_Front

I've already generate the registry with JH4.0.6 and it works.
It only miss a check of my work by @jdubois (I'm his intern at Ippon currently).

What do you prefer ?
Make somes PR during the migration (by merge the Front and the Back branches), or make only a final PR when the complete migration will be OK ?

**Comment by deepu105** [comment]
Seperate smaller PRs will easier to review and merge than a big bang


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Yes small PR are always better
You can probably make one big PR to start the migration, as the architecture has changed.

**Comment by g-boy05** [comment]
I shared the tasks with @mohamed2a and @heronakam I will work on admin and history modules and @heronakam will work about the other modules

**Comment by g-boy05** [comment]
@mohamed2a If you can update the fence tasks for Admin page #97 
@heronakam

**Comment by mohamed2a** [comment]
@g-boy05 your changes must be merged before, I'm waiting for it :-)

**Comment by g-boy05** [comment]
@mohamed2a ok because @pascalgrimaud sent a mail as he will work on this I think he didn't  see @heronakam PR

**Comment by JulienMrgrd** [comment]
All admin pages are now OK ! (see #99)
